const wordPhonetics: Record<string, string> = {
  "atmosphere": "/ˈætməsˌfɪɹ/",
  "hydrosphere": "",
  "lithosphere": "",
  "oxygen": "/ˈɒksɪdʒən/",
  "oxide": "/ˈɒksaɪd/",
  "carbon dioxide": "/ˈkɑɹbən/ /daɪˈɒksaɪd/",
  "hydrogen": "/ˈhaɪdɹədʒən/",
  "core": "/kɔɹ/",
  "crust": "/kɹʌst/",
  "mantle": "/ˈmæn.təl/",
  "longitude": "/ˈlɑndʒəˌtud/",
  "latitude": "/ˈlæt.ə.tjud/",
  "horizon": "/həˈɹaɪzən/",
  "altitude": "/ˈælt.ɪˌtjuːd/",
  "disaster": "/dɪˈzæs.tɚ/",
  "mishap": "/ˈmɪs.hæp/",
  "catastrophic": "/kætəˈstɹɒfɪk/",
  "calamity": "/kəˈlæmɪti/",
  "endanger": "/ənˈdeɪndʒə/",
  "jeopardise": "",
  "jeopardize": "",
  "destructive": "/dɪˈstɹʊktɪv/",
  "El Nino": "/ɛl/",
  "greenhouse": "/ˈɡɹiːnˌhaʊs/",
  "phenomenon": "/fɪˈnɒmənɒn/",
  "pebble": "/ˈpɛb.əl/",
  "magnet": "/ˈmæɡnət/",
  "ore": "/ɔɹ/",
  "mineral": "/ˈmɪ.nəɹ.əl/",
  "marble": "",
  "quartz": "",
  "granite": "",
  "gust": "",
  "breeze": "",
  "monsoon": "",
  "gale": "",
  "hurricane": "",
  "tornado": "",
  "typhoon": "",
  "volcano": "",
  "erupt": "",
  "magma": "",
  "thermodynamic": "",
  "smog": "",
  "fume": "",
  "mist": "",
  "tsunami": "",
  "drought": "",
  "flooding": "",
  "torrent": "",
  "earthquake": "",
  "seismic": "",
  "avalanche": "",
  "terrain": "",
  "landscape": "",
  "continent": "",
  "cave": "",
  "cliff": "",
  "glacier": "",
  "swamp": "",
  "delta": "",
  "plain": "",
  "plateau": "/plæˈtoʊ/",
  "oasis": "",
  "globe": "/ɡloːb/",
  "hemisphere": "/ˈhɛmɪsfɪəɹ/",
  "equator": "/ɪˈkweɪ.tə/",
  "arctic": "",
  "Antarctic": "/ænˈtɑːktɪk/",
  "pole": "/poʊl/",
  "polar": "/ˈpəʊ̯lə(ɹ)/",
  "axis": "/ˈæksɪs/",
  "deteriorate": "/dɪˈtɪəɹɪəɹeɪt/",
  "aggravate": "/ˈæɡ.ɹə.veɪ̯t/",
  "degrade": "/diˈɡɹeɪd/",
  "upgrade": "/ˈʌp.ɡɹeɪd/",
  "erode": "/ɪˈɹoʊd/",
  "Mediterranean": "",
  "Atlantic": "",
  "pacific": "/pəˈsɪfɪk/",
  "ocean": "/ˈoʊ.ʃən/",
  "marine": "/məˈɹiːn/",
  "navigation": "/nævɪˈɡeɪʃən/",
  "gulf": "/ɡʌlf/",
  "beach": "/biːt͡ʃ/",
  "coast": "/koʊst/",
  "shore": "/ʃɔɹ/",
  "tide": "/taɪd/",
  "current": "/ˈkɝɹənt/",
  "brook": "/bɹʊk/",
  "stream": "/stɹiːm/",
  "source": "/sɔːs/",
  "shallow": "/ˈʃæl.oʊ/",
  "superficial": "/ˌsupɚˈfɪʃəl/",
  "flat": "/flæt/",
  "smooth": "/smuːð/",
  "rough": "/ɹʌf/",
  "sandy": "/ˈsændi/",
  "stony": "/ˈstəʊni/",
  "vertical": "",
  "steep": "",
  "parallel": "",
  "narrow": "",
  "Oceania": "",
  "mainland": "",
  "peninsula": "",
  "climate": "",
  "weather": "",
  "meteorology": "",
  "mild": "",
  "heating": "",
  "moderate": "",
  "warm": "",
  "thermal": "",
  "tropics": "",
  "arid": "",
  "moist": "",
  "damp": "",
  "humid": "",
  "snowy": "",
  "frost": "",
  "hail": "",
  "thaw": "",
  "chill": "",
  "freeze": "",
  "frigid": "",
  "tremble": "",
  "shiver": "",
  "thunder": "/ˈθʌndɚ/",
  "lightning": "/ˈlaɪt.nɪŋ/",
  "stormy": "/ˈstɔɹmi/",
  "downpour": "/ˈdaʊn.pɔː(ɹ)/",
  "rainfall": "",
  "sprinkle": "/ˈspɹɪŋkəl/",
  "rainbow": "/ˈɹeɪmboʊ/",
  "shower": "/ˈʃəʊ.ə(ɹ)/",
  "Celsius": "",
  "temperature": "/ˈtɛmp(ə)ɹətʃə(ɹ)/",
  "forecast": "/ˈfɔɹkæst/",
  "peak": "/piːk/",
  "mount": "/maʊnt/",
  "mountain": "/ˈmaʊntɪn/",
  "range": "/ɹeɪndʒ/",
  "ridge": "/ɹɪdʒ/",
  "slope": "/sloʊp/",
  "valley": "/ˈvæli/",
  "hillside": "",
  "overlook": "/oʊvəɹˈlʊk/",
  "southern": "/ˈsʌðɚn/",
  "southeast": "",
  "southwest": "/saʊˈwɛst/",
  "northeast": "",
  "northwest": "",
  "eastern": "/ˈiːstən/",
  "oriental": "",
  "inevitable": "/ɪnˈɛvɪtəbəl/",
  "irreversible": "",
  "irregularly": "/ɪˈɹɛɡjʊləli/",
  "inappropriate": "/ˌɪnəˈpɹəʊpɹi.ət/",
  "abnormal": "/əbˈnɔɹ.ml̩/",
  "sediment": "/ˈsɛd.ɪ.mənt/",
  "silt": "/sɪlt/",
  "muddy": "[ˈmʌdi]",
  "clay": "/kleɪ/",
  "dirt": "/dɝt/",
  "rural": "/ˈɹɔːɹəl/",
  "suburb": "/ˈsʌbɜːb/",
  "outskirts": "/ˈaʊtskɝts/",
  "remote": "[ɹɪˈmoʊt]",
  "desolate": "",
  "distant": "/ˈdɪstənt/",
  "adjacent": "/əˈdʒeɪ.sənt/",
  "toxic": "/ˈtɒk.sɪk/",
  "pollution": "/pəˈl(j)uːʃn̩/",
  "pollutant": "",
  "contaminate": "/kənˈtæmɪneɪt/",
  "geology": "/dʒiˈɑlədʒi/",
  "border": "/ˈbɔːdə/",
  "margin": "/ˈmɑːɹdʒ(ə)n/",
  "fringe": "/fɹɪndʒ/",
  "plate": "",
  "debris": "",
  "crack": "",
  "gap": "",
  "splendid": "",
  "grand": "",
  "magnificent": "",
  "super": "",
  "interesting": "",
  "dramatic": "",
  "wilderness": "",
  "desert": "",
  "deforest": "",
  "barren": "",
  "fertile": "",
  "fertilise": "",
  "fertilize": "",
  "solar": "",
  "lunar": "",
  "calendar": "",
  "sunrise": "",
  "sunset": "",
  "eclipse": "",
  "dusk": "",
  "heaven": "",
  "paradise": "",
  "sunshine": "",
  "shade": "",
  "shadow": "",
  "vapour": "",
  "vapor": "",
  "evaporate": "",
  "circulate": "",
  "precipitate": "",
  "reservoir": "",
  "waterfall": "/ˈwɔtɚfɔl/",
  "fountain": "[ˈfaʊn.ʔn̩]",
  "spring": "/spɹɪŋ/",
  "dew": "/djuː/",
  "pour": "/pɔɹ/",
  "drain": "/dɹeɪn/",
  "drip": "/dɹɪp/",
  "drown": "/dɹaʊn/",
  "blow": "/bloʊ/",
  "puff": "/pʌf/",
  "gush": "/ˈɡʌʃ/",
  "dense": "/dɛns/",
  "intensity": "/ɪnˈtɛnsɪti/",
  "intensive": "/ɪnˈtɛnsɪv/",
  "emerge": "/iˈmɜːd͡ʒ/",
  "flash": "/flæʃ/",
  "float": "/floʊt/",
  "environment": "/-mɪnt/",
  "surrounding": "/səˈɹaʊndɪŋ/",
  "condition": "/kənˈdɪʃən/",
  "situation": "/sɪtjuːˈeɪʃən/",
  "nature": "/ˈneɪtʃə/",
  "natural": "/-ɚəl/",
  "artificial": "/ɑː(ɹ)təˈfɪʃəl/",
  "synthetic": "",
  "petrol": "",
  "gas": "",
  "gasoline": "",
  "petroleum": "",
  "photosynthesis": "",
  "respire": "",
  "dioxide": "",
  "vegetation": "",
  "herb": "",
  "perennial": "",
  "botany": "",
  "ecology": "",
  "ecosystem": "",
  "eco-friendly": "",
  "horticulture": "",
  "organism": "",
  "genetics": "",
  "mutation": "",
  "variation": "",
  "diversity": "",
  "hybridisation": "",
  "hybridization": "",
  "classify": "",
  "reproduce": "",
  "evolve": "",
  "fluctuate": "",
  "reclaim": "",
  "cultivate": "",
  "sow": "",
  "harvest": "",
  "pluck": "/plʌk/",
  "pick": "/pɪk/",
  "yield": "/jiːld/",
  "rear": "/ɹiɹ/",
  "arable": "/ˈæɹəbl̩/",
  "plough": "/plaʊ/",
  "plow": "",
  "spade": "/speɪd/",
  "rake": "/ɹeɪk/",
  "stack": "/stæk/",
  "heap": "/hiːp/",
  "bundle": "/ˈbʌnd(ə)l/",
  "bunch": "/ˈbʌntʃ/",
  "vase": "/veɪs/",
  "sunlight": "/ˈsʌnˌlaɪt/",
  "short-day": "/ʃoːt/ /deɪ/",
  "shade-tolerant": "/ʃeɪd/ /ˈtɒləɹənt/",
  "fungus": "/ˈfʌŋ.ɡəs/",
  "mould": "/moʊld/",
  "mold": "/moʊld/",
  "pollen": "/ˈpɑlən/",
  "germinate": "",
  "seed": "/siːd/",
  "burgeon": "/ˈbɝː.d͡ʒən/",
  "bud": "",
  "flower": "",
  "blossom": "",
  "bloom": "",
  "scent": "",
  "aromatic": "",
  "ripen": "",
  "fruit": "",
  "wither": "",
  "decompose": "",
  "rot": "",
  "decay": "",
  "stale": "",
  "rainforest": "",
  "jungle": "",
  "plantation": "",
  "field": "",
  "terrace": "",
  "timber": "",
  "charcoal": "",
  "log": "",
  "logo": "",
  "forestry": "",
  "branch": "",
  "trunk": "",
  "bough": "",
  "root": "",
  "hay": "",
  "straw": "",
  "reed": "",
  "thorn": "",
  "weed": "",
  "grass": "[ɡɹ̠ɑːs]",
  "meadow": "/ˈmɛdoʊ/",
  "lawn": "/lɔn/",
  "olive": "/ˈɒlɪv/",
  "pine": "/paɪn/",
  "vine": "/vaɪn/",
  "violet": "/ˈvaɪlət/",
  "tulip": "/ˈt(j)uːlɪp/",
  "mint": "/mɪnt/",
  "reef": "/ɹiːf/",
  "alga": "/ˈæl.ɡə/",
  "enzyme": "/ˈɛn.zaɪm/",
  "catalyst": "/ˈkæt.əl.ɪst/",
  "release": "/ɹɪˈliːs/",
  "emission": "/ɪˈmɪʃn̩/",
  "absorb": "/æbˈsɔɹb/",
  "circulation": "/ˌsɝkjʊˈleɪʃən/",
  "exceed": "/ɪkˈsiːd/",
  "uptake": "",
  "nutrient": "/ˈnjuː.tɹi.ənt/",
  "energy": "/ˈɛnɚd͡ʒi/",
  "surroundings": "/səˈɹaʊndɪŋz/",
  "mechanism": "/ˈmɛkənɪzm/",
  "counterbalance": "/ˌkaʊntə(ɹ)ˈbæləns/",
  "protect": "/pɹəˈtɛkt/",
  "preserve": "/pɹəˈzɝv/",
  "conservation": "/ˌkɑnsə(ɹ)ˈveɪʃən/",
  "bush fire": "/bʊʃ/ /ˈfaɪɚ/",
  "extinguish": "/ɪkˈstɪŋ.ɡwɪʃ/",
  "destruct": "",
  "ruin": "/ˈɹuː.ɪn/",
  "perish": "/ˈpɛɹɪʃ/",
  "demolish": "/dəˈmɒl.ɪʃ/",
  "infringe": "/ɪnˈfɹɪndʒ/",
  "undermine": "/ʌndəˈmaɪn/",
  "extinction": "/ɪkˈstɪŋkʃ(ə)n/",
  "pattern": "/ˈpat(ə)n/",
  "outcome": "/ˈaʊtkʌm/",
  "impact": "",
  "seasonal": "/ˈsiːzənəl/",
  "experimental": "/ɨkspɛɹəˈmɛntəl/",
  "favourable": "/ˈfeɪv(ə)ɹəbəl/",
  "favorable": "",
  "productive": "/pɹəˈdʌktɪv/",
  "effective": "/əˈfɛktɪv/",
  "efficient": "/əˈfɪʃənt/",
  "considerable": "/kənˈsɪdəɹəbl̩/",
  "massive": "/ˈmæs.ɪv/",
  "immense": "/ɪˈmɛns/",
  "maximal": "",
  "minimal": "/mɪnəməl/",
  "optimal": "/ˈɑptɪməl/",
  "optimum": "/ˈɒptɪməm/",
  "biologist": "",
  "zoologist": "/zəʊˈɒlədʒɪst/",
  "ecologist": "",
  "botanist": "/ˈbɒt.ən.ɪst/",
  "mammal": "/ˈmæməl/",
  "primate": "/ˈpɹaɪmeɪt/",
  "vertebrate": "/ˈvɛɹ.tɪ.bɹeɪt/",
  "reptile": "/ɹɪpˈtaɪl/",
  "amphibian": "/æmˈfɪbɪən/",
  "carnivore": "/ˈkɑːnɪvɔː/",
  "herbivore": "/ˈhɜːbɪvɔː(ɹ)/",
  "creature": "/ˈkɹiːt͡ʃəɹ/",
  "wildlife": "/ˈwaɪldlaɪf/",
  "fauna": "/ˈfɔː.nə/",
  "flora": "/ˈflɔː.ɹə/",
  "species": "/ˈspiːsiːz/",
  "flock": "/flɑk/",
  "herd": "/hɝd/",
  "swarm": "/swɔɹm/",
  "throng": "",
  "crowd": "",
  "beast": "",
  "brute": "",
  "cruel": "",
  "originate": "",
  "derive": "",
  "stem": "",
  "ancestor": "",
  "descendant": "",
  "offspring": "",
  "subgroup": "",
  "feed": "",
  "breed": "",
  "interbreed": "",
  "hybridize": "",
  "hybridise": "",
  "proliferate": "",
  "sterility": "",
  "mate": "",
  "courtship": "",
  "lay": "",
  "hatch": "",
  "brood": "",
  "spawn": "",
  "mature": "",
  "skin": "",
  "claw": "",
  "paw": "",
  "beak": "",
  "fin": "",
  "wing": "",
  "plume": "/ˈplum/",
  "feather": "/ˈfɛð.ɚ/",
  "fur": "/fɝ/",
  "bristle": "/ˈbɹɪs.l̩/",
  "curl": "/kɝl/",
  "insect": "/ˈɪnsɛkt/",
  "worm": "/wɝm/",
  "pest": "/pɛst/",
  "parasite": "/ˈpæɹəˌsaɪt/",
  "spider": "/ˈspaɪ̯dɚ/",
  "butterfly": "/ˈbʌtə(ɹ)flaɪ/",
  "mosquito": "/mɒsˈkiː.təʊ/",
  "cricket": "/ˈkɹɪk.ɪt/",
  "penguin": "/ˈpɛŋɡwɪn/",
  "seal": "/siːl/",
  "tortoise": "/ˈtɔːɹ.təs/",
  "turtle": "/ˈtɝtəl/",
  "whale": "/weɪl/",
  "kangaroo": "/kaŋ.ɡə.ˈɹuː/",
  "camel": "/ˈkæməl/",
  "panda": "/ˈpændə/",
  "elephant": "/ˈɛləfənt/",
  "ivory": "/ˈaɪvəɹi/",
  "horn": "/hɔːn/",
  "bear": "/bɑɹ/",
  "wolf": "/wʊlf/",
  "dragon": "/ˈdɹæɡən/",
  "fox": "/fɑks/",
  "cub": "/kʌb/",
  "calf": "/kæf/",
  "pup": "/pʌp/",
  "lamb": "/læm/",
  "cattle": "/ˈkæt(ə)l/",
  "ox": "/ˈɒks/",
  "bull": "/ˈbʊl/",
  "buffalo": "/ˈbʌf.əl.əʊ/",
  "horse": "/hɔɹs/",
  "zebra": "/ˈziːbɹə/",
  "donkey": "/ˈdɑŋki/",
  "saddle": "/ˈsædəl/",
  "harness": "/ˈhɑː(ɹ).nəs/",
  "falcon": "/ˈfælkən/",
  "hawk": "/hɔk/",
  "eagle": "/ˈiːɡəl/",
  "owl": "/aʊl/",
  "swallow": "/ˈswɑloʊ/",
  "sparrow": "/ˈspæɹoʊ/",
  "pigeon": "/ˈpɪ.dʒən/",
  "crow": "/kɹoʊ/",
  "swan": "",
  "goose": "",
  "cock": "",
  "mouse": "",
  "rat": "",
  "squirrel": "",
  "hare": "",
  "frog": "",
  "behaviour": "",
  "behavior": "",
  "bite": "",
  "sting": "",
  "bark": "",
  "roar": "",
  "rub": "",
  "creep": "",
  "crawl": "",
  "habitat": "",
  "nest": "",
  "hive": "",
  "cell": "",
  "cage": "",
  "stable": "",
  "barn": "",
  "hedge": "",
  "barrier": "",
  "bar": "",
  "anatomy": "",
  "epidemic": "",
  "gene": "",
  "germ": "",
  "bacteria": "",
  "virus": "/ˈvaɪɹəs/",
  "microbe": "/ˈmaɪkɹoʊb/",
  "metabolism": "/mɪˈtab.əl.ɪz.əm/",
  "protein": "/ˈpɹoʊtiːn/",
  "vitamin": "/ˈvaɪ.tə.mɪn/",
  "secrete": "/sɪˈkɹiːt/",
  "excrete": "/ɛkˈskɹiːt/",
  "devour": "/dɪˈvaʊ(w)ə(ɹ)/",
  "instinct": "/ˈɪn.stɪŋkt/",
  "intuitive": "/ɪnˈtjuːɪtɪv/",
  "potential": "/po(ʊ)ˈtɛnʃəl/",
  "intelligence": "/ɪnˈtɛl.ɪ.d͡ʒəns/",
  "functional": "/ˈfʌŋk(t)ʃnəl/",
  "sensitive": "/ˈsɛnsɪtɪv/",
  "flexible": "/ˈflɛk.sə.bəl/",
  "acoustic": "/əˈkuːstɪk/",
  "optical": "/ˈɒptɪkəl/",
  "nocturnal": "/nɑkˈtɚnəl/",
  "dormant": "/ˈdɔːmənt/",
  "hibernation": "/ˌhaɪ.bəːˈneɪ.ʃən/",
  "track": "/tɹæk/",
  "trace": "/tɹeɪs/",
  "alternate": "",
  "prey": "/pɹeɪ/",
  "predator": "/ˈpɹɛd.ə.təɹ/",
  "victim": "/ˈvɪktəm/",
  "captive": "/ˈkæptɪv/",
  "defensive": "/dɪˈfɛnsɪv/",
  "undergo": "/ˌʌndəˈɡəʊ/",
  "suffer": "/ˈsʌfɚ/",
  "vulnerable": "/ˈvʌln(ə)ɹəbl̩/",
  "subsistence": "",
  "exist": "",
  "exterminate": "",
  "tame": "",
  "keeper": "",
  "shepherd": "",
  "galaxy": "",
  "cosmos": "",
  "universe": "",
  "interstellar": "",
  "terrestrial": "",
  "celestial": "",
  "astronomy": "",
  "astrology": "",
  "astronaut": "",
  "comet": "",
  "meteorite": "",
  "crater": "",
  "dust": "",
  "ash": "/æʃ/",
  "envelope": "",
  "chunk": "",
  "spacecraft": "",
  "spaceship": "",
  "probe": "/pɹəʊb/",
  "module": "/ˈmɒdjuːl/",
  "propulsion": "/pɹəˈpʌlʃən/",
  "pressure": "[ˈpɹɛʃ.ɚ]",
  "dynamics": "",
  "motion": "/ˈmoʊʃən/",
  "vent": "/vɛnt/",
  "tail": "/teɪl/",
  "curve": "/kɝv/",
  "exploration": "/ˌɛkspləˈɹeɪʃən/",
  "expedition": "/ɛkspəˈdɪʃən/",
  "flyby": "",
  "observatory": "/əbˈzəɹvətɔɹi/",
  "telescope": "/ˈtɛləˌskoʊp/",
  "spectacle": "/ˈspɛktəkl̩/",
  "orbit": "/ˈɔː(ɹ)bɪt/",
  "ecliptic": "/ɪˈklɪp.tɪk/",
  "diameter": "/daɪˈæmɪtɚ/",
  "radius": "/ˈɹeɪ.di.əs/",
  "substance": "/ˈsʌbstəns/",
  "composition": "/ˌkɒmpəˈzɪʃən/",
  "compound": "/ˈkɒmpaʊnd/",
  "fossil": "/ˈfɑːsəl/",
  "sample": "/sæːm.pəl/",
  "specimen": "",
  "particle": "",
  "molecule": "",
  "atom": "",
  "ion": "",
  "electron": "",
  "quantum": "",
  "liquid": "",
  "fluid": "",
  "solid": "",
  "synthesise": "",
  "synthesize": "",
  "formation": "",
  "method": "",
  "spectrum": "",
  "dimension": "",
  "frequency": "",
  "signal": "",
  "antenna": "",
  "circuit": "",
  "refraction": "",
  "ultraviolet": "",
  "radioactive": "",
  "distinct": "",
  "discernible": "",
  "invisible": "",
  "collision": "",
  "squash": "",
  "fragment": "",
  "cataclysmic": "",
  "overwhelming": "",
  "despair": "",
  "desperate": "",
  "hopeless": "",
  "education": "",
  "primary": "",
  "secondary": "",
  "university": "",
  "college": "",
  "institute": "",
  "academy": "",
  "learn": "",
  "study": "",
  "acquire": "",
  "knowledge": "",
  "expertise": "",
  "novice": "",
  "recruit": "",
  "literate": "",
  "illiteracy": "/ɪˈlɪt(ʃ)ɹəsi/",
  "numerate": "/ˈnjuːməɹət/",
  "problem": "/ˈpɹɑbləm/",
  "issue": "/ˈɪsjuː/",
  "affair": "/əˈfɛə(ɹ)/",
  "controversial": "/kɒn.tɹə.ˈvɜː.sjəl/",
  "puzzle": "/ˈpʌzəl/",
  "riddle": "/ˈɹɪdəl/",
  "obscure": "/əbˈskjɝ/",
  "instil": "/ɪnˈstɪl/",
  "instill": "/ɪnˈstɪl/",
  "cram": "/kɹæm/",
  "emphasise": "",
  "emphasize": "/ˈɛm.fə.saɪz/",
  "enhance": "/ɪnˈhæns/",
  "enable": "/ɪˈneɪbəl/",
  "inspire": "/ɪn.ˈspaɪə(ɹ)/",
  "motive": "/ˈmoʊtɪv/",
  "motivate": "/ˈməʊtɪveɪt/",
  "stimulate": "/ˈstɪmjʊleɪt/",
  "spur": "/spɝ/",
  "impetus": "/ˈɪm.pə.təs/",
  "indulge": "/ɪnˈdʌldʒ/",
  "spoil": "/spɔɪl/",
  "abuse": "/əˈbjus/",
  "intelligent": "/ɪnˈtɛlɪd͡ʒənt/",
  "clever": "",
  "smart": "",
  "all-round": "",
  "all-around": "",
  "genius": "",
  "elite": "",
  "idiot": "",
  "wisdom": "",
  "wit": "",
  "aptitude": "",
  "capable": "",
  "excellent": "",
  "outstanding": "",
  "brilliant": "",
  "prestige": "",
  "reputation": "",
  "eminent": "",
  "notorious": "",
  "esteem": "",
  "respect": "",
  "diligent": "",
  "painstaking": "",
  "skill": "",
  "approach": "",
  "scheme": "",
  "headmaster": "",
  "principal": "",
  "dean": "",
  "faculty": "",
  "professor": "",
  "scholar": "",
  "scientist": "",
  "mentor": "",
  "tutor": "",
  "lecturer": "",
  "assistant": "",
  "candidate": "",
  "degree": "",
  "qualify": "",
  "certify": "",
  "license": "",
  "licence": "",
  "permit": "",
  "diploma": "/dɪˈpləʊmə/",
  "diplomat": "/ˈdɪ.plə.mæt/",
  "ambassador": "/æmˈbæs.ə.də(ɹ)/",
  "pupil": "/ˈpjuːpəl/",
  "graduate": "",
  "ceremony": "/ˈsɛɹəmoʊni/",
  "bachelor": "/ˈbætʃ.lɚ/",
  "master": "/ˈmæstɚ/",
  "doctor": "/ˈdɒktə/",
  "fresher": "/ˈfɹɛʃə/",
  "sophomore": "/ˈsɒfəmɔɹ/",
  "junior": "/ˈdʒuːnɪə/",
  "senior": "/ˈsinjɚ/",
  "alumni": "/əˈlʌmnaɪ/",
  "campus": "/ˈkæmpəs/",
  "orientation": "/ˌɔɹiɛnˈteɪʃən/",
  "platform": "/ˈplætfɔɹm/",
  "coed": "",
  "co-educational": "/koʊ/ /ˌɛdʒʊˈkeɪʃənəl/",
  "register": "/ˈɹɛdʒ.ɪs.tɚ/",
  "roster": "/ˈɹɑstɚ/",
  "enrol": "",
  "enroll": "/ɪnˈɹəʊl/",
  "matriculation": "",
  "accommodation": "/ə.ˌkɒm.ə.ˈdeɪ.ʃən/",
  "dorm": "",
  "dining hall": "",
  "canteen": "",
  "laboratory": "",
  "lab": "",
  "experiment": "",
  "data": "",
  "quantity": "",
  "quality": "",
  "library": "",
  "literature": "",
  "article": "",
  "author": "",
  "tale": "",
  "fiction": "",
  "story": "",
  "diary": "",
  "poetry": "",
  "magazine": "",
  "journal": "",
  "coverage": "",
  "bibliography": "",
  "encyclopedia": "",
  "encyclopaedia": "",
  "biography": "",
  "documentary": "",
  "series": "",
  "record": "",
  "file": "",
  "profile": "",
  "draft": "",
  "sketch": "",
  "brochure": "",
  "manual": "",
  "frame": "",
  "index": "",
  "catalogue": "",
  "catalog": "",
  "category": "",
  "inventory": "",
  "content": "",
  "context": "",
  "list": "",
  "chapter": "",
  "volume": "",
  "reel": "/ɹiːl/",
  "subject": "/ˈsʌb.dʒɛkt/",
  "object": "/ˈɑb.d͡ʒɛkt/",
  "major": "/ˈmeɪ.dʒɚ/",
  "minor": "/ˈmaɪnɚ/",
  "sociology": "/ˌsəʊsiːˈɒlədʒiː/",
  "politics": "/ˈpɒl.ɪ.tɪks/",
  "economics": "/ˌikəˈnɑmɪks/",
  "marketing": "",
  "accounting": "/ə.ˈkaʊn.tɪŋ/",
  "audit": "/ɔː.dɪt/",
  "statistics": "/stəˈtɪstɪks/",
  "psychology": "/saɪˈkɑlədʒi/",
  "philosophy": "/fɪˈlɑsəfi/",
  "logic": "/ˈlɑdʒɪk/",
  "biology": "/baɪˈɑlədʒi/",
  "physics": "/ˈfɪz.ɪks/",
  "chemistry": "/ˈkɛm.ɪ.stɹi/",
  "agriculture": "/ˈæɡɹɪˌkʌltʃə/",
  "logistics": "",
  "geography": "/dʒiˈɑɡɹəfi/",
  "history": "/ˈhɪst(ə)ɹi/",
  "engineering": "/ˌen.dʒɪˈnɪə.ɹɪŋ/",
  "mechanics": "",
  "electronics": "",
  "maths": "",
  "mathematics": "",
  "arithmetic": "",
  "geometry": "",
  "algebra": "",
  "calculus": "",
  "plus": "",
  "sum": "",
  "total": "",
  "merger": "",
  "equation": "",
  "identical": "",
  "minus": "",
  "subtract": "",
  "multiply": "",
  "divide": "",
  "dividend": "",
  "remainder": "",
  "rational": "",
  "parameter": "",
  "variable": "",
  "even": "",
  "odd": "",
  "mean": "",
  "double": "",
  "triple": "",
  "quadruple": "",
  "multiple": "",
  "maximum": "",
  "minimum": "",
  "approximately": "",
  "chart": "",
  "graph": "",
  "diagram": "",
  "table": "",
  "matrix": "",
  "rectangle": "",
  "cube": "",
  "angle": "",
  "triangle": "",
  "diagonal": "",
  "straight": "",
  "circle": "",
  "round": "",
  "dot": "",
  "sphere": "",
  "cone": "",
  "extent": "",
  "width": "/ˈwɪdθ/",
  "length": "",
  "decimal": "/ˈdɛsɪməl/",
  "percent": "/pɚˈsɛnt/",
  "per cent": "/pɚˈsɛnt/",
  "proportion": "/pɹəˈpɔɹʃən/",
  "rate": "/ɹeɪt/",
  "ratio": "/ˈɹeɪ.ʃiˌoʊ/",
  "fraction": "/ˈfɹæk.ʃən/",
  "scale": "/skeɪl/",
  "ounce": "/aʊns/",
  "density": "/ˈdɛn.sə.ti/",
  "Fahrenheit": "",
  "mercury": "/ˈmɝkjəɹi/",
  "battery": "/ˈbætəɹi/",
  "volt": "/vɒlt/",
  "radiate": "/ˈɹeɪdi.ət/",
  "emit": "/iˈmɪt/",
  "transparent": "/tɹæn(t)sˈpæɹənt/",
  "hollow": "/hɑlɚ/",
  "ozone": "/ˈoʊzoʊn/",
  "gravity": "/ˈɡɹævɪti/",
  "friction": "/ˈfɹɪkʃən̩/",
  "eccentric": "/ɛkˈsɛntɹɪk/",
  "displace": "/dɪsˈpleɪs/",
  "boil": "/bɔɪl/",
  "melt": "/mɛlt/",
  "dissolve": "/dɪˈzɒlv/",
  "rust": "",
  "ferment": "",
  "dilute": "",
  "acid": "",
  "noxious": "",
  "static": "",
  "inert": "",
  "inherent": "",
  "formula": "",
  "component": "",
  "compose": "",
  "mixture": "",
  "blend": "",
  "theory": "",
  "empirical": "",
  "practical": "",
  "doctrine": "",
  "principle": "",
  "discipline": "",
  "term": "",
  "semester": "",
  "timetable": "",
  "schedule": "",
  "deadline": "",
  "course": "",
  "lesson": "",
  "curriculum": "",
  "seminar": "",
  "forum": "",
  "syllabus": "",
  "system": "",
  "rudimentary": "",
  "basic": "",
  "fundamental": "",
  "elementary": "",
  "profound": "",
  "surface": "",
  "compulsory": "",
  "prerequisite": "",
  "selective": "",
  "elective": "",
  "assignment": "",
  "submit": "",
  "preview": "",
  "review": "",
  "revise": "/ɹɪˈvaɪ̯z/",
  "inspect": "/ɪnˈspɛkt/",
  "consult": "",
  "skim": "/skɪm/",
  "scan": "/skæn/",
  "scrutinise": "",
  "scrutinize": "/ˈskɹuːtɨnaɪz/",
  "recite": "/ɹɪˈsaɪt/",
  "dictate": "/ˈdɪkˌteɪt/",
  "examination": "/ɪɡˌzæmɪˈneɪʃən/",
  "exam": "/ɛɡˈzæm/",
  "test": "/test/",
  "quiz": "/kwɪz/",
  "presentation": "/ˌpɹizənˈteɪʃən/",
  "plagiarise": "",
  "plagiarize": "",
  "copy": "/ˈkɑpi/",
  "print": "/pɹɪnt/",
  "thesis": "/ˈθisɪs/",
  "essay": "/ˈɛˌseɪ/",
  "paper": "/ˈpeɪpə/",
  "dissertation": "/ˌdɪsəˈteɪʃən/",
  "project": "",
  "heading": "[ˈhɛɾ.ɪŋ]",
  "outset": "/ˈaʊtsɛt/",
  "outline": "/ˈaʊtlaɪn/",
  "point": "/pɔɪnt/",
  "gist": "/dʒɪst/",
  "opinion": "",
  "introduce": "",
  "reference": "",
  "cite": "",
  "elicit": "",
  "quote": "",
  "extract": "",
  "abstract": "",
  "summary": "",
  "assume": "",
  "presume": "",
  "suppose": "",
  "hypothesis": "",
  "postulate": "",
  "speculate": "",
  "predict": "",
  "perceive": "",
  "detect": "",
  "discern": "",
  "recognise": "",
  "recognize": "",
  "conscious": "",
  "reckon": "",
  "deem": "",
  "imply": "",
  "deliberate": "",
  "represent": "",
  "insist": "",
  "persist": "",
  "understand": "",
  "comprehend": "",
  "analyse": "",
  "analyze": "",
  "diagnose": "",
  "infer": "",
  "deduce": "",
  "conclude": "",
  "analogy": "",
  "compare": "",
  "contrast": "",
  "overlap": "",
  "contradiction": "",
  "disagree": "",
  "differ": "",
  "diverse": "/daɪ.ˈvɝs/",
  "nuance": "",
  "inductive": "",
  "detail": "",
  "thorough": "/ˈθʌɹə/",
  "example": "/əɡˈzæmpl̩/",
  "instance": "",
  "confirm": "/kənˈfɝm/",
  "demonstrate": "/ˈdɛmənstɹeɪt/",
  "illustrate": "/ɪ.ˈlʌs.tɹeɪt/",
  "manifest": "/ˈmæn.ə.fɛst/",
  "prove": "/pɹuːv/",
  "determine": "/dɪˈtɜːmɪn/",
  "decide": "/dɪˈsaɪd/",
  "resolve": "/ɹɪˈzɑlv/",
  "survey": "",
  "research": "/ɹiˈsɝtʃ/",
  "observe": "/əbˈzɝv/",
  "inquire": "/ɪnˈkwaɪɹ/",
  "enquire": "/ɪŋˈkwaɪə/",
  "query": "/ˈkwɪə.ɹi/",
  "questionnaire": "/ˌk(w)estjəˈnɛə/",
  "achieve": "/əˈtʃiːv/",
  "accomplish": "/əˈkɑm.plɪʃ/",
  "attain": "/əˈteɪn/",
  "credit": "/ˈkɹɛdɪt/",
  "score": "/skɔɹ/",
  "mark": "/mɑɹk/",
  "grade": "/ɡɹeɪd/",
  "rank": "/ɹæŋk/",
  "row": "/ˈɹoʊ/",
  "queue": "/kjuː/",
  "grant": "",
  "praise": "",
  "appreciate": "",
  "feedback": "",
  "underestimate": "",
  "overestimate": "",
  "apply": "",
  "fellowship": "",
  "scholarship": "",
  "reward": "",
  "award": "",
  "prize": "",
  "fee": "",
  "technology": "",
  "technique": "",
  "polytechnic": "",
  "engineer": "",
  "mechanic": "",
  "advance": "",
  "innovate": "",
  "breakthrough": "",
  "gizmo": "",
  "patent": "",
  "devise": "",
  "invent": "",
  "discover": "",
  "disclose": "",
  "reveal": "",
  "uncover": "",
  "expose": "",
  "domain": "",
  "realm": "",
  "foundation": "",
  "specialise": "",
  "specialize": "",
  "concentrate": "",
  "focus": "",
  "utilise": "",
  "utilize": "",
  "usage": "",
  "tester": "",
  "device": "",
  "appliance": "",
  "facility": "",
  "equipment": "",
  "instrument": "",
  "tool": "/tuːl/",
  "gauge": "/ˈɡeɪdʒ/",
  "measure": "/ˈmɛʒə/",
  "calculate": "/ˈkælkjəleɪt/",
  "compute": "/kəmˈpjuːt/",
  "count": "/kaʊnt/",
  "estimate": "/ˈɛstɨmɨt/",
  "assess": "/əˈsɛs/",
  "evaluate": "/ɪ̈ˈvaljəˌweɪt/",
  "accessory": "/ækˈsɛsəɹi/",
  "byproduct": "",
  "auxiliary": "/ɔːkˈsɪli.əɹi/",
  "versatile": "/ˈvɜːsətaɪl/",
  "add": "/æd/",
  "accumulate": "/ə.ˈkjum.jə.ˌleɪt/",
  "assemble": "/əˈsɛmbl̩/",
  "gather": "/ˈɡæðɚ/",
  "attach": "/əˈtætʃ/",
  "belong": "/bɪˈlɔŋ/",
  "optics": "/ˈɒptɪks/",
  "microscope": "/ˈmaɪkɹəˌskəʊp/",
  "lens": "/lɛnz/",
  "radar": "/ˈɹeɪdɚ/",
  "echo": "/ˈɛkoʊ/",
  "sensor": "/ˈsɛn.sɚ/",
  "multimedia": "/mʌltiˈmiːdi.ə/",
  "network": "/nɛtwɝk/",
  "browser": "/ˈbɹaʊzə(ɹ)/",
  "dial": "/ˈdaɪəɫ/",
  "microcomputer": "",
  "laptop": "/ˈlæp.tɒp/",
  "software": "",
  "keyboard": "",
  "screen": "",
  "loudspeaker": "",
  "microphone": "",
  "cassette": "",
  "tape": "",
  "binary": "",
  "digital": "",
  "wireless": "",
  "high-definition": "",
  "audio": "",
  "vision": "",
  "fantasy": "",
  "science fiction": "",
  "sci-fi": "",
  "pump": "",
  "generator": "",
  "gear": "",
  "pivot": "",
  "hydraulic": "",
  "drainage": "",
  "sewage": "",
  "ventilation": "",
  "compress": "",
  "condense": "",
  "refine": "",
  "simplify": "",
  "purify": "",
  "filter": "",
  "distil": "",
  "distill": "",
  "mode": "",
  "prototype": "",
  "framework": "",
  "aspect": "",
  "phase": "",
  "operate": "",
  "facilitate": "",
  "transform": "",
  "convert": "/ˈkɑn.vəɹt/",
  "alter": "/ˈɔl.tɚ/",
  "shift": "/ʃɪft/",
  "turn": "/tɝn/",
  "adapt": "/əˈdæpt/",
  "adjust": "/əˈdʒʌst/",
  "pinpoint": "",
  "accurate": "/ˈæk.jə.ɹɪt/",
  "precise": "/pɹɪˈsaɪs/",
  "correct": "/kəˈɹɛkt/",
  "error": "/ˈɛɹɚ/",
  "mistake": "/mɪˈsteɪk/",
  "flaw": "/ˈflɔ/",
  "wrong": "/ɹɔŋ/",
  "fault": "/fɒlt/",
  "stumble": "/ˈstʌmbəl/",
  "contingency": "/kənˈtɪndʒənsi/",
  "circumstance": "/ˈsɝ.kəm.ˌstæns/",
  "culture": "/ˈkʌlt͡ʃə/",
  "civilisation": "/ˌsɪv.ɪ.lɪˈzeɪ.ʃən/",
  "civilization": "[ˌsɪv.ə.lɑeˈzæɪ.ʃən]",
  "renaissance": "/ˈɹɛnəˌsɑns/",
  "epic": "/ˈɛp.ɪk/",
  "ideology": "/aɪ.di.ˈɑl.ə.d͡ʒi/",
  "tradition": "/tɹəˈdɪʃn̩/",
  "convention": "/kənˈvɛn.ʃən/",
  "custom": "/ˈkʌstəm/",
  "feudalism": "/ˈfju.dəlɪzəm/",
  "slavery": "/ˈsleɪvəɹi/",
  "ethical": "/ˈɛθɪkəl/",
  "moral": "/ˈmɑɹəl/",
  "tribe": "",
  "aboriginal": "",
  "inhabitant": "",
  "native": "",
  "local": "",
  "exotic": "",
  "foreigner": "",
  "alien": "",
  "anthropologist": "",
  "humanitarian": "",
  "heritage": "",
  "inherit": "",
  "antique": "",
  "archaeology": "",
  "excavate": "",
  "museum": "",
  "pottery": "",
  "engrave": "",
  "decorate": "",
  "religion": "",
  "ritual": "",
  "etiquette": "",
  "belief": "",
  "soul": "",
  "spirit": "",
  "sacred": "",
  "hallowed": "",
  "holy": "",
  "Pope": "",
  "bishop": "",
  "missionary": "",
  "priest": "",
  "Bible": "",
  "church": "",
  "cathedral": "",
  "choir": "",
  "monk": "",
  "temple": "",
  "pagoda": "",
  "empire": "",
  "imperial": "",
  "royal": "",
  "dynasty": "",
  "chronology": "",
  "emperor": "",
  "king": "",
  "queen": "",
  "prince": "/pɹɪns/",
  "princess": "/ˈpɹɪnsɛs/",
  "majesty": "/ˈmædʒ.əs.ti/",
  "nobility": "/nəʊˈbɪlɪti/",
  "lord": "/lɔːd/",
  "knight": "/naɪt/",
  "guardian": "/ˈɡɑɹdi.ən/",
  "nostalgia": "/nɒˈstaldʒə/",
  "homesick": "",
  "celebrity": "/sɪˈlɛbɹɪti/",
  "status": "/ˈsteɪt.əs/",
  "background": "/ˈbæk.ɡɹaʊnd/",
  "experience": "/ɪkˈspɪə.ɹɪəns/",
  "anecdote": "/ˈæ.nɪk.doʊt/",
  "accident": "/ˈæk.sə.dənt/",
  "incident": "/ˈɪn.sɪ.dənt/",
  "thrive": "/θɹaɪv/",
  "prosperity": "/pɹɑˈspɛɹ.ɪ.ti/",
  "setback": "/ˈsɛtbæk/",
  "adversity": "/ædˈvɜː.sɪ.ti/",
  "language": "[ˈleɪŋɡwɪd͡ʒ]",
  "symbol": "/ˈsɪmbəl/",
  "sign": "/saɪn/",
  "gesture": "/ˈdʒɛs.tʃɚ/",
  "handwriting": "/ˈhændɹaɪtɪŋ/",
  "pictograph": "",
  "wedge": "/wɛdʒ/",
  "knot": "/nɑt/",
  "linguistics": "/liŋˈɡwɪstɪks/",
  "semantic": "/sɪˈmæntɪk/",
  "syntax": "/ˈsɪn.tæks/",
  "grammar": "",
  "phonetics": "",
  "pronounce": "",
  "intonation": "",
  "inflection": "",
  "dialect": "",
  "accent": "",
  "utterance": "",
  "oral": "",
  "verbal": "",
  "syllable": "",
  "phoneme": "",
  "vowel": "",
  "consonant": "",
  "alphabet": "",
  "logogram": "",
  "vocabulary": "",
  "dictionary": "",
  "idiom": "",
  "phrase": "",
  "clause": "",
  "expression": "",
  "tense": "",
  "prefix": "",
  "suffix": "",
  "abbreviation": "",
  "synonym": "",
  "antonym": "",
  "noun": "",
  "singular": "",
  "plural": "",
  "pronoun": "",
  "verb": "",
  "adjective": "",
  "adverb": "",
  "preposition": "",
  "conjunction": "",
  "consistent": "",
  "complicated": "",
  "complex": "",
  "compile": "",
  "version": "",
  "translate": "",
  "paraphrase": "",
  "interpret": "",
  "narrate": "",
  "illuminate": "/ɪlˈl(j)uməneɪt/",
  "decipher": "/dɪˈsaɪfə(ɹ)/",
  "eloquence": "/ˈɛl.ə.kwəns/",
  "communicate": "/kəˈmjuːnɪkeɪt/",
  "discussion": "/dɪˈskʌʃən/",
  "brainstorm": "/ˈbɹeɪnstɔː(ɹ)m/",
  "debate": "/dɪˈbeɪt/",
  "commentary": "",
  "negotiate": "/nəˈɡoʊ.ʃi.eɪt/",
  "contention": "/kənˈtɛnʃən/",
  "medium": "/ˈmiːdɪəm/",
  "press": "/pɹɛs/",
  "journalist": "/ˈdʒɜːnəlɪst/",
  "critic": "/ˈkɹɪt.ɪk/",
  "commentator": "/ˈkɑmənˌteɪtəɹ/",
  "exponent": "/ɛkˈspəʊnənt/",
  "announcer": "/əˈnaʊnsə/",
  "correspondent": "/ˌkɔɹɪˈspɑndənt/",
  "messenger": "/ˈmɛs.n̩.d͡ʒɚ/",
  "editor": "/ˈɛdɪtə/",
  "typist": "/ˈtaɪpɪst/",
  "handout": "/ˈhændaʊt/",
  "leaflet": "/ˈliːflɪt/",
  "propaganda": "[ˌpɹɑp.ə.ˈɡæn.də]",
  "publish": "/ˈpʌblɪʃ/",
  "disseminate": "/dɪˈsɛmɪˌneɪt/",
  "foresee": "/fɔɹˈsi/",
  "anticipate": "/ænˈtɪs.ə.peɪt/",
  "expect": "/ɛkˈspɛkt/",
  "await": "/əˈwɛɪt/",
  "pastime": "/ˈpæs.taɪm/",
  "entertain": "/ˌɛntɚˈteɪn/",
  "recreation": "/ɹɛkɹiˈeɪʃən/",
  "amuse": "/əˈmjuːz/",
  "gossip": "/ˈɡɑs.ɪp/",
  "rumour": "/ˈɹuːmə(ɹ)/",
  "rumor": "/ˈɹuːmə(ɹ)/",
  "consensus": "",
  "festival": "",
  "feast": "",
  "programme": "",
  "program": "",
  "rehearsal": "",
  "perform": "",
  "imitate": "",
  "mimic": "",
  "simulate": "",
  "circus": "",
  "magic": "",
  "drama": "",
  "concert": "",
  "symphony": "",
  "orchestra": "",
  "ballet": "",
  "opera": "",
  "comedy": "",
  "tragedy": "",
  "animation": "",
  "film": "",
  "movie": "",
  "X-rated": "",
  "artist": "",
  "craftsman": "",
  "painter": "",
  "role": "",
  "scene": "",
  "stage": "",
  "gallery": "",
  "exhibition": "",
  "aesthetic": "",
  "esthetic": "",
  "collect": "",
  "select": "",
  "opt": "",
  "photograph": "",
  "portrait": "",
  "painting": "",
  "sculpture": "",
  "draw": "",
  "depict": "",
  "describe": "/dəˈskɹaɪb/",
  "carve": "/kɑːv/",
  "improvise": "",
  "musical": "/ˈmju.zɪ.kəl/",
  "classical": "/ˈklæsɪkl̩/",
  "jazz": "/d͡ʒæz/",
  "rock": "/ɹɑk/",
  "hip-hop": "/hɪp/ /hɑp/",
  "pop": "/pɒp/",
  "lyric": "/ˈlɪɹ.ɪk/",
  "band": "/bænd/",
  "solo": "/ˈsoʊ.loʊ/",
  "melody": "/ˈmɛl.ə.di/",
  "rhythm": "/ˈɹɪ.ð(ə)m/",
  "tone": "/toʊn/",
  "tune": "/tjuːn/",
  "disc": "/dɪsk/",
  "disk": "/dɪsk/",
  "piano": "/piˈænəʊ/",
  "violin": "/ˌvaɪəˈlɪn/",
  "cello": "/ˈtʃɛloʊ/",
  "guitar": "/ɡɪˈtɑː(ɹ)/",
  "harmonica": "/ˌhɑɹ.ˈmɒ.nɪ.kə/",
  "trumpet": "/ˈtɹʌmpɪt/",
  "drum": "/ˈdɹʌm/",
  "flute": "/fluːt/",
  "competition": "/ˌkɑːmpəˈtɪʃən/",
  "tournament": "/ˈtɔːnəmənt/",
  "Olympic": "",
  "sponsor": "/ˈspɒn.sə/",
  "patron": "/ˈpeɪ.tɹən/",
  "athlete": "/ˈæθ.lit/",
  "champion": "/ˈtʃæmpiən/",
  "spectator": "/ˈspɛkteɪtɚ/",
  "volunteer": "/vɑl.ənˈtɪɹ/",
  "famous": "/ˈfeɪməs/",
  "well-known": "/ˌwɛlˈnəʊn/",
  "energetic": "",
  "vigorous": "",
  "stadium": "",
  "gym": "",
  "training": "",
  "exercise": "",
  "indoor": "",
  "outdoor": "",
  "mobile": "",
  "movement": "",
  "yoga": "",
  "sprawl": "",
  "stretch": "",
  "strain": "",
  "chess": "",
  "badminton": "",
  "golf": "",
  "billiards": "",
  "soccer": "",
  "tennis": "",
  "volleyball": "",
  "hockey": "",
  "goal": "",
  "bat": "",
  "racket": "",
  "kick": "",
  "knock": "",
  "flip": "",
  "pitch": "",
  "throw": "",
  "toss": "",
  "slide": "",
  "slip": "",
  "glide": "",
  "tumble": "",
  "ski": "",
  "skate": "",
  "cycling": "",
  "dive": "",
  "drift": "",
  "jump": "",
  "leap": "",
  "plunge": "",
  "hop": "",
  "bounce": "",
  "tent": "",
  "camp": "[kʰɛəmp]",
  "picnic": "/ˈpɪknɪk/",
  "hunt": "/hʌnt/",
  "race": "/ɹeɪs/",
  "marathon": "/ˈmæɹəθən/",
  "pedestrian": "/pəˈdɛst.ɹi.ən/",
  "pace": "/peɪs/",
  "step": "/stɛp/",
  "excursion": "/ɛks.kɜː(ɹ).ʃən/",
  "cruise": "/kɹuːz/",
  "trip": "/tɹɪp/",
  "vacation": "/veɪˈkeɪʃən/",
  "hike": "/haɪk/",
  "jog": "/dʒɑɡ/",
  "stride": "/stɹaɪd/",
  "wander": "/ˈwɑndɚ/",
  "linger": "/ˈlɪŋɡə/",
  "lag": "/læɡ/",
  "climb": "/klaɪm/",
  "pull": "/pʊl/",
  "drag": "/dɹæɡ/",
  "bend": "/bɛnd/",
  "bow": "/bəʊ/",
  "stuff": "/stʌf/",
  "item": "[ˈaɪ̯ɾm̩]",
  "merchandise": "/ˈmɜːtʃənˌdaɪs/",
  "souvenir": "/ˌsuːvəˈnɪə(ɹ)/",
  "artifact": "/ˈɑːtɪfækt/",
  "artefact": "",
  "material": "/məˈtɪəɹɪəl/",
  "raw": "/ɹɔː/",
  "crude": "/kɹuːd/",
  "necessity": "/nɪˈsɛsəti/",
  "outfit": "/ˈaʊtfɪt/",
  "kit": "",
  "utensil": "",
  "garbage": "",
  "rubbish": "",
  "trash": "",
  "recycle": "",
  "reuse": "",
  "litter": "",
  "waste": "",
  "junk": "",
  "landfill": "",
  "sewerage": "",
  "detergent": "",
  "lotion": "",
  "shampoo": "",
  "soap": "",
  "tub": "",
  "plug": "",
  "tap": "",
  "pipe": "",
  "tube": "",
  "mop": "",
  "broom": "",
  "sweep": "",
  "mattress": "",
  "carpet": "",
  "rug": "",
  "mat": "",
  "cushion": "",
  "pad": "",
  "blanket": "",
  "quilt": "",
  "sheet": "",
  "pillow": "",
  "sponge": "",
  "towel": "",
  "staple": "",
  "nail": "",
  "razor": "",
  "shave": "",
  "fuse": "",
  "cable": "",
  "cord": "",
  "strand": "",
  "match": "",
  "candle": "",
  "wax": "",
  "portfolio": "",
  "paperback": "",
  "pamphlet": "/ˈpæmf.lɪt/",
  "tissue": "",
  "cover": "",
  "Xerox": "/ˈzɛ.ɹɒks/",
  "duplicate": "",
  "memorandum": "",
  "stationery": "/ˈsteɪʃ(ə)n(ə)ɹi/",
  "glue": "/ɡluː/",
  "ink": "/iŋk/",
  "rubber": "/ˈɹʌbɚ/",
  "scissors": "/ˈsɪzəz/",
  "shear": "/ʃiɹ/",
  "edge": "/ɛdʒ/",
  "rim": "/ɹɪm/",
  "element": "/ˈɛlɪmənt/",
  "factor": "/ˈfæktɚ/",
  "section": "/ˈsɛkʃən/",
  "tag": "/teɪɡ/",
  "label": "/ˈleɪbəl/",
  "badge": "/bædʒ/",
  "bolt": "/boʊlt/",
  "knob": "/nɒb/",
  "handle": "/ˈhæn.dl/",
  "shutter": "/ˈʃʌtɚ/",
  "curtain": "/ˈkɜːtn̩/",
  "pane": "/peɪn/",
  "opacity": "/oʊˈpæsɪtiː/",
  "jar": "/dʒɐː/",
  "barrel": "/ˈbæɹəl/",
  "bucket": "/ˈbʌkɪt/",
  "pail": "/peɪl/",
  "phone": "/fəʊ̯n/",
  "bell": "/bɛl/",
  "camera": "/ˈkæməɹə/",
  "portable": "/ˈpɔː(ɹ)təbl̩/",
  "spotlight": "",
  "lantern": "",
  "bulb": "",
  "flashlight": "",
  "refrigerator": "",
  "fridge": "",
  "vacuum": "",
  "fan": "",
  "switch": "",
  "hurdle": "",
  "fence": "",
  "pedal": "",
  "shelf": "",
  "ladder": "",
  "lift": "",
  "stool": "",
  "drawer": "",
  "umbrella": "",
  "raincoat": "",
  "dredge": "",
  "can": "",
  "mill": "",
  "forge": "",
  "alloy": "",
  "metal": "",
  "iron": "",
  "lead": "",
  "brass": "",
  "bronze": "",
  "cement": "",
  "lime": "",
  "plaster": "",
  "leather": "",
  "plastic": "",
  "fiber": "",
  "fibre": "",
  "fabric": "",
  "knit": "",
  "weave": "",
  "canvas": "",
  "linen": "",
  "cotton": "",
  "nylon": "/ˈnaɪlɒn/",
  "lumber": "",
  "wooden": "",
  "mine": "/maɪn/",
  "pit": "/ˈpɪt/",
  "fuel": "/ˈfjuːl/",
  "lubricate": "",
  "diamond": "/ˈdaɪ(ə)mənd/",
  "crystal": "/ˈkɹɪstəl/",
  "inferior": "/ɪnˈfɪ(ə)ɹiɚ/",
  "counterfeit": "/ˈkaʊn.tɚˌfɪt/",
  "fake": "/feɪk/",
  "fragile": "/ˈfɹædʒəl/",
  "miniature": "/ˈmɪn(ɪ)ətʃə(ɹ)/",
  "available": "/əˈveɪləb(ə)l/",
  "durable": "/ˈd(j)ʊəɹəbəl/",
  "fashion": "/ˈfæʃən/",
  "style": "/staɪl/",
  "trend": "/tɹɛnd/",
  "tendency": "/ˈtɛndənsi/",
  "popularity": "/ˌpɒp.jəˈlæɹ.ɪ.ti/",
  "vogue": "/vəʊɡ/",
  "prevail": "/pɹɪˈveɪl/",
  "model": "/ˈmɑdl̩/",
  "icon": "/ˈaɪ.kɑːn/",
  "idol": "/ˈaɪd(ə)l/",
  "luxury": "/ˈlʌkʃəɹi/",
  "extravagant": "/ɪkˈstɹævəɡənt/",
  "jewelry": "",
  "jewellery": "/ˈdʒuːlɹi/",
  "jewel": "/dʒul/",
  "gem": "/d͡ʒɛm/",
  "jade": "/d͡ʒeɪd/",
  "adorn": "/əˈdɔɹn/",
  "ornament": "/ˈɔɹnəmənt/",
  "embellish": "/ɛm-/",
  "embroider": "/ɪmˈbɹɔɪdɚ/",
  "hairdressing": "",
  "pigment": "/ˈpɪɡ.mənt/",
  "dye": "/daɪ/",
  "masquerade": "/ˈmæskəˌɹeɪd/",
  "veil": "/veɪl/",
  "costume": "/ˈkɒs.tjuːm/",
  "fascinate": "/ˈfæsɪneɪt/",
  "decent": "/ˈdiːsənt/",
  "exquisite": "/ɪkˈskwɪzɪt/",
  "grace": "",
  "elegance": "",
  "perfect": "",
  "appearance": "",
  "cosmetics": "",
  "make-up": "",
  "handsome": "",
  "charming": "",
  "pretty": "",
  "beautiful": "",
  "ugly": "",
  "dress": "",
  "clothe": "",
  "uniform": "",
  "garment": "",
  "laundry": "",
  "wardrobe": "",
  "overall": "",
  "overcoat": "",
  "robe": "",
  "gown": "",
  "sweater": "",
  "jacket": "",
  "skirt": "",
  "jeans": "",
  "trousers": "",
  "clasp": "",
  "button": "",
  "glove": "",
  "hat": "",
  "cap": "",
  "brim": "",
  "scarf": "",
  "handkerchief": "",
  "purse": "",
  "wallet": "/ˈwɒlɪt/",
  "vest": "/vɛst/",
  "wrap": "/ɹæp/",
  "cloak": "/ˈkloʊk/",
  "collar": "/ˈkɑ.lɚ/",
  "sleeve": "/sliːv/",
  "sock": "/sɑk/",
  "stocking": "/ˈstɑkɪŋ/",
  "slipper": "",
  "boot": "/but/",
  "lace": "/leɪs/",
  "tailor": "/ˈteɪlɚ/",
  "sew": "/soʊ/",
  "spin": "/spɪn/",
  "stitch": "/stɪt͡ʃ/",
  "needle": "/ˈniː.dl/",
  "pin": "/pɪn/",
  "string": "/stɹɪŋ/",
  "thread": "[θɾ̪̊ɛd]",
  "strap": "/stɹæp/",
  "stripe": "/st(ʃ)ɹʌɪp/",
  "ribbon": "/ˈɹɪbən/",
  "belt": "/bɛlt/",
  "chain": "/ˈt͡ʃeɪn/",
  "bracelet": "/ˈbɹeɪslət/",
  "necklace": "/ˈnɛkləs/",
  "bead": "/biːd/",
  "textile": "/ˈtɛks.taɪl/",
  "velvet": "/ˈvɛlvət/",
  "wool": "/wʊl/",
  "patch": "/pætʃ/",
  "rag": "/ɹæɡ/",
  "shabby": "/ˈʃæb.i/",
  "tight": "",
  "colour": "",
  "color": "/ˈkʌl.ɚ/",
  "white": "/waɪt/",
  "yellow": "/jɛlə/",
  "brown": "/bɹaʊn/",
  "grey": "",
  "gray": "",
  "pink": "",
  "purple": "",
  "tan": "",
  "fade": "",
  "stain": "",
  "blot": "",
  "figure": "",
  "slender": "",
  "slight": "",
  "food": "",
  "diet": "",
  "appetite": "",
  "treat": "",
  "cater": "",
  "provision": "",
  "edible": "",
  "recipe": "",
  "restaurant": "",
  "refectory": "",
  "cafeteria": "",
  "buffet": "",
  "barbecue": "",
  "supper": "",
  "banquet": "",
  "refreshment": "",
  "snack": "",
  "appetiser": "",
  "appetizer": "",
  "cuisine": "",
  "menu": "",
  "order": "",
  "takeaway": "",
  "chef": "",
  "gourmet": "",
  "vegetarian": "",
  "cutlery": "",
  "silver": "",
  "ceramic": "",
  "porcelain": "",
  "bowl": "",
  "dish": "",
  "saucer": "",
  "tray": "",
  "fork": "/fɔːk/",
  "knife": "/naɪf/",
  "spoon": "/spuːn/",
  "glass": "/ɡlɑːs/",
  "mug": "/mʌɡ/",
  "kettle": "/ˈkɛ.təl/",
  "pan": "/pæn/",
  "pot": "/pɑt/",
  "stove": "/stoʊv/",
  "furnace": "/ˈfɝnɪs/",
  "oven": "/ˈʌ.vn̩/",
  "tin": "/tɪn/",
  "lid": "/lɪd/",
  "drink": "/dɹɪŋk/",
  "beverage": "/ˈbevəɹɪdʒ/",
  "juice": "/d͡ʒus/",
  "soda": "/ˈsəʊdə/",
  "coffee": "/ˈkɒ.fi/",
  "alcohol": "/ˈæl.kə.hɒl/",
  "liquor": "/ˈlɪk.ə(ɹ)/",
  "whisky": "/ˈwɪski/",
  "whiskey": "/ˈwɪski/",
  "brandy": "/ˈbɹændi/",
  "drunk": "/dɹʌŋk/",
  "tobacco": "/təˈbækoʊ/",
  "cigarette": "/sɪ.ɡəˈɹɛt/",
  "sober": "/ˈsəʊ.bə(ɹ)/",
  "vegetable": "/ˈvɛd͡ʒtəbəl/",
  "tomato": "[tʰə̥ˈmɐːtʰɐʉ]",
  "potato": "/pəˈteɪ.təʊ/",
  "pea": "/piː/",
  "bean": "/biːn/",
  "cucumber": "",
  "cabbage": "",
  "onion": "",
  "mushroom": "",
  "eggplant": "",
  "carrot": "",
  "turnip": "",
  "radish": "",
  "peel": "",
  "strip": "",
  "hull": "",
  "cherry": "",
  "berry": "",
  "grape": "",
  "papaya": "",
  "peach": "",
  "pear": "",
  "plum": "",
  "orange": "",
  "melon": "",
  "lemon": "",
  "kiwi": "",
  "crop": "",
  "corn": "",
  "grain": "",
  "wheat": "",
  "reap": "",
  "flour": "",
  "porridge": "",
  "paste": "",
  "livestock": "",
  "chicken": "",
  "turkey": "",
  "beef": "",
  "pork": "",
  "mutton": "",
  "sausage": "",
  "fish": "",
  "pond": "",
  "rod": "",
  "dairy": "",
  "milk": "",
  "yogurt": "",
  "cream": "",
  "cheese": "",
  "butter": "",
  "salad": "",
  "sandwich": "/ˈsæmˌwɪt͡ʃ/",
  "hamburger": "/ˈhæm.bə.ɡə/",
  "loaf": "/ləʊf/",
  "pie": "",
  "pizza": "/ˈpiːt.sə/",
  "pasta": "/ˈpɐːstə/",
  "spaghetti": "[spəˈɡɛɾi]",
  "soup": "/suːp/",
  "pudding": "/ˈpʊd.ɪŋ/",
  "biscuit": "/ˈbɪskɪt/",
  "jam": "/ˈdʒæm/",
  "nut": "/nʌt/",
  "chocolate": "/ˈt͡ʃɔk(ə)lət/",
  "ice cream": "/aɪs/ /kɹiːm/",
  "vanilla": "/vəˈnɛlə/",
  "mustard": "[ˈmɐs.təd]",
  "wasabi": "/wəˈsɑːbi/",
  "pepper": "/ˈpɛpə/",
  "ginger": "/ˈdʒɪndʒə/",
  "garlic": "/ˈɡɑːlɪk/",
  "scallion": "[ˈskæ.ljn̩]",
  "vinegar": "/ˈvɪnəɡə/",
  "salt": "/sɒlt/",
  "sugar": "/ˈʃʊɡə(ɹ)/",
  "candy": "/ˈkændi/",
  "honey": "/ˈhʌni/",
  "flavor": "/ˈfleɪvɚ/",
  "flavour": "",
  "sour": "/ˈsaʊ(ə)ɹ/",
  "sweet": "/swit/",
  "bitter": "/ˈbɪtəɹ/",
  "spicy": "",
  "delicious": "",
  "yummy": "",
  "tasty": "",
  "hunger": "",
  "thirsty": "",
  "spice": "",
  "sauce": "",
  "ketchup": "",
  "perfume": "",
  "ingredient": "",
  "supplement": "",
  "digest": "",
  "cook": "",
  "bake": "",
  "fry": "",
  "roast": "",
  "toast": "",
  "suck": "",
  "lick": "",
  "chew": "",
  "gum": "",
  "soak": "",
  "dip": "",
  "squeeze": "",
  "stir": "",
  "grind": "",
  "slice": "",
  "architecture": "",
  "erection": "",
  "structure": "",
  "construct": "",
  "obstruct": "",
  "establish": "",
  "build": "",
  "found": "",
  "concrete": "",
  "steel": "",
  "stability": "",
  "site": "",
  "venue": "",
  "landmark": "",
  "situated": "",
  "locate": "",
  "reside": "",
  "inhabit": "",
  "migrate": "",
  "settle": "/ˈsɛtəl/",
  "dwelling": "",
  "skyscraper": "/ˈskaɪˌskɹeɪp.ə(ɹ)/",
  "villa": "/ˈvɪlə/",
  "mansion": "/ˈmæn(t)ʃən/",
  "apartment": "/əˈpɑːt.mənt/",
  "hostel": "/ˈhɑstəl/",
  "lodge": "/lɑdʒ/",
  "hut": "/hʌt/",
  "cabin": "/ˈkæbɪn/",
  "cellar": "/ˈsɛlə(ɹ)/",
  "shed": "/ʃɛd/",
  "cottage": "/ˈkɑtədʒ/",
  "nursery": "/ˈnɜːsəɹi/",
  "cradle": "/ˈkɹeɪdəl/",
  "shelter": "/ˈʃɛltɚ/",
  "block": "/blɑk/",
  "grid": "/ɡɹɪd/",
  "aisle": "/aɪ̯l/",
  "porch": "/pɔɹtʃ/",
  "corridor": "/ˈkɔɹəˌdɔɹ/",
  "stair": "/stɛəɹ/",
  "staircase": "/ˈstɛɹˌkeɪs/",
  "storey": "/ˈstɔːɹi/",
  "layer": "/ˈleɪ.ɚ/",
  "elevator": "/ˈɛl.ə.veɪ.tɚ/",
  "escalator": "/ˈɛs.kə.leɪ.tə/",
  "handrail": "",
  "pillar": "/ˈpɪlɚ/",
  "column": "/ˈkɑljəm/",
  "beam": "/biːm/",
  "vault": "",
  "arch": "",
  "ceiling": "",
  "eaves": "",
  "chimney": "",
  "reception": "",
  "lobby": "",
  "bench": "",
  "parlour": "",
  "parlor": "",
  "fireplace": "",
  "radiator": "",
  "living room": "",
  "cabinet": "",
  "balcony": "",
  "kitchen": "",
  "lavatory": "",
  "toilet": "",
  "bath": "",
  "basin": "",
  "reserve": "",
  "store": "",
  "mall": "",
  "supermarket": "",
  "booth": "",
  "casino": "",
  "studio": "",
  "downtown": "",
  "urban": "",
  "peripheral": "",
  "vicinity": "",
  "room": "",
  "void": "",
  "spacious": "",
  "airtight": "",
  "expanse": "",
  "plaza": "",
  "castle": "",
  "carpenter": "",
  "mason": "",
  "tile": "",
  "brickwork": "",
  "suspension": "",
  "hook": "",
  "lever": "/ˈliː.və/",
  "scaffold": "",
  "infrastructure": "/ˈɪnfɹəˌstɹʌk(t)ʃɚ/",
  "apparatus": "/æ.pəˈɹæ.təs/",
  "crane": "/kɹeɪn/",
  "malfunction": "/ˌmælˈfʌŋk.ʃən/",
  "maintain": "/meɪnˈteɪn/",
  "fix": "/ˈfɪks/",
  "mend": "/mɛnd/",
  "modify": "/ˈmɑdɪfaɪ/",
  "trim": "/tɹɪm/",
  "weld": "/wɛld/",
  "saw": "/sɔ/",
  "screw": "/skɹuː/",
  "drill": "/dɹɪl/",
  "plumb": "/plʌm/",
  "viaduct": "/ˈvaɪəˌdʌkt/",
  "span": "/spæn/",
  "dam": "/dæm/",
  "install": "/ɪnˈstɔːl/",
  "furnish": "/ˈfɝnɪʃ/",
  "placement": "/ˈpleɪsmənt/",
  "layout": "/ˈleɪ.aʊt/",
  "design": "/dɪˈzaɪn/",
  "entrance": "/ˈɛn.tɹəns/",
  "entry": "/ˈɛntɹi/",
  "enter": "",
  "exit": "",
  "outside": "",
  "outward": "",
  "exterior": "",
  "external": "",
  "inner": "",
  "interior": "",
  "inward": "",
  "internal": "",
  "navigate": "",
  "voyage": "",
  "aviation": "",
  "journey": "",
  "travel": "",
  "safari": "",
  "parade": "",
  "haunt": "",
  "attraction": "",
  "memorial": "",
  "pyramid": "",
  "port": "",
  "visa": "",
  "traffic": "",
  "airline": "",
  "airplane": "",
  "helicopter": "",
  "jet": "",
  "parachute": "",
  "flight": "",
  "pilot": "",
  "passenger": "",
  "baggage": "",
  "luggage": "",
  "suitcase": "",
  "carry-on": "",
  "rack": "",
  "freight": "",
  "fare": "",
  "atlas": "",
  "route": "",
  "itinerary": "",
  "passage": "",
  "intersection": "/ˈɪntəɹˌsɛkʃən/",
  "cross": "/kɹɔs/",
  "way": "/weɪ/",
  "path": "[pʰɑːθ]",
  "lane": "/leɪn/",
  "avenue": "/ˈæv.əˌnjuː/",
  "highway": "/ˈhaɪweɪ/",
  "curb": "/kɜːb/",
  "signpost": "",
  "pave": "/peɪv/",
  "vehicle": "/ˈvi.ə.kəl/",
  "auto": "/ˈɑtoʊ/",
  "express": "/ɛk.ˈspɹɛs/",
  "tram": "/tɹam/",
  "coach": "/koʊtʃ/",
  "ambulance": "/ˈæm.bjə.ləns/",
  "truck": "/tɹʌk/",
  "lorry": "/ˈlɒɹi/",
  "van": "/væn/",
  "wagon": "/ˈwæɡən/",
  "carriage": "/ˈkæɹɪdʒ/",
  "tractor": "/ˈtɹæktɚ/",
  "cart": "/kɑɹt/",
  "pedicab": "/ˈpɛdiˌkæb/",
  "cycle": "/ˈsaɪkəl/",
  "garage": "/ɡəˈɹɑː(d)ʒ/",
  "motor": "/ˈmoʊtɚ/",
  "horsepower": "/ˈhɔɹsˌpaʊɚ/",
  "wheel": "/wil/",
  "brake": "/bɹeɪk/",
  "tire": "/ˈtʌɪ̯ɚ/",
  "tyre": "/taɪə(ɹ)/",
  "honk": "/hɒŋk/",
  "crew": "",
  "captain": "",
  "steward": "",
  "emergency": "",
  "wreck": "",
  "crash": "",
  "crush": "",
  "dash": "",
  "vanish": "",
  "disappear": "",
  "hazard": "",
  "harbour": "",
  "harbor": "",
  "dock": "",
  "anchor": "",
  "submerge": "",
  "sailor": "",
  "seaman": "",
  "carrier": "",
  "steamer": "",
  "liner": "",
  "vessel": "",
  "ferry": "",
  "sail": "",
  "raft": "",
  "canoe": "",
  "oar": "",
  "deck": "",
  "turbine": "",
  "propeller": "",
  "stern": "",
  "aboard": "",
  "embark": "",
  "channel": "",
  "canal": "",
  "ditch": "",
  "railroad": "",
  "railway": "",
  "locomotive": "",
  "subway": "",
  "underground": "",
  "tunnel": "",
  "rail": "",
  "depart": "",
  "arrive": "",
  "destination": "",
  "delay": "/dɪˈleɪ/",
  "postpone": "/poʊstˈpoʊn/",
  "defer": "/dɪˈfɜː(ɹ)/",
  "lull": "/lʌl/",
  "expire": "/ɛkˈspaɪ.ə(ɹ)/",
  "due": "/du/",
  "postage": "/ˈpəʊstɪdʒ/",
  "stamp": "/stæmp/",
  "mail": "/meɪ̯l/",
  "packet": "/ˈpak.ɪt/",
  "package": "/ˈpækɪdʒ/",
  "bind": "/baɪnd/",
  "parcel": "[ˈpʰɑɹ.səɫ]",
  "load": "/loʊd/",
  "burden": "/ˈbɝdn/",
  "transfer": "/tɹænzˈfɜː/",
  "transmit": "/tɹænsˈmɪt/",
  "transit": "/ˈtɹæn.sɪt/",
  "deliver": "/dɪˈlɪvɚ/",
  "convey": "/kənˈveɪ/",
  "speed": "/spiːd/",
  "velocity": "/vəˈlɑsəti/",
  "swift": "/swɪft/",
  "republic": "[ɹɪˈpʌblɪk]",
  "Marxism": "",
  "socialism": "",
  "communism": "",
  "regime": "",
  "government": "",
  "authority": "",
  "political": "",
  "hierarchy": "",
  "democracy": "",
  "bureaucracy": "",
  "egalitarian": "",
  "materialism": "",
  "revolution": "",
  "reform": "",
  "process": "",
  "conservative": "",
  "meltdown": "",
  "municipal": "",
  "neutral": "",
  "bilateral": "",
  "arena": "",
  "flag": "",
  "banner": "",
  "president": "",
  "premier": "",
  "minister": "",
  "secretary": "",
  "parliament": "",
  "senate": "",
  "conference": "",
  "meeting": "",
  "headquarters": "",
  "delegation": "",
  "behalf": "",
  "police": "",
  "statesman": "",
  "mayor": "",
  "service": "",
  "office": "",
  "bureau": "",
  "department": "",
  "administration": "",
  "dominate": "",
  "power": "",
  "influence": "",
  "affect": "",
  "importance": "",
  "significance": "/sɪɡˈnɪfɪkəns/",
  "organization": "",
  "organisation": "/ˌɔɹɡənɪˈzeɪʃən/",
  "association": "/əˌsoʊsiˈeɪʃən/",
  "union": "/ˈjuːnjən/",
  "community": "/k(ə)ˈmjunəti/",
  "consortium": "/kənˈsɔː(ɹ).ti.əm/",
  "league": "/liːɡ/",
  "institution": "/ˌɪnstɪˈtuːʃən/",
  "unite": "/juˈnaɪt/",
  "unique": "/juːˈniːk/",
  "nation": "/ˈneɪ.ʃən/",
  "global": "/ˈɡləʊbəl/",
  "worldwide": "/ˈwɝldˌwaɪd/",
  "federal": "/ˈfɛdəɹəl/",
  "foreign": "/ˈfɒɹən/",
  "overseas": "/ˌəʊvəˈsiːz/",
  "abroad": "/əˈbɹɔd/",
  "civil": "/ˈsɪv.əl/",
  "emigrate": "/ˈɛmɪɡɹeɪt/",
  "immigrate": "/ˈɪmɪɡɹeɪt/",
  "reign": "[ɹeɪn]",
  "puppet": "/ˈpʌpɪt/",
  "throne": "[θɹoʊn]",
  "crown": "/kɹaʊn/",
  "wreath": "/ɹiːθ/",
  "colony": "/ˈkɑləniː/",
  "liberty": "",
  "independence": "",
  "slum": "",
  "refuge": "",
  "asylum": "",
  "population": "",
  "demographic": "",
  "citizen": "",
  "resident": "",
  "ethnic": "",
  "racial": "",
  "clan": "",
  "franchise": "",
  "entitle": "",
  "preference": "",
  "vote": "",
  "elect": "",
  "respondent": "",
  "poll": "",
  "ambition": "",
  "nominate": "",
  "checklist": "",
  "succession": "",
  "safety": "",
  "welfare": "",
  "well-being": "",
  "harmony": "",
  "steady": "",
  "flourish": "",
  "succeed": "",
  "prospect": "",
  "perspective": "",
  "viewpoint": "",
  "standpoint": "",
  "outlook": "",
  "guideline": "",
  "ethic": "",
  "suggest": "",
  "advise": "",
  "proposal": "",
  "hint": "",
  "declare": "",
  "affirm": "/əˈfɝm/",
  "claim": "/kleɪm/",
  "proclaim": "",
  "state": "/steɪt/",
  "announce": "/əˈnaʊns/",
  "clarify": "/ˈklæɹɪfaɪ/",
  "assist": "/əˈsɪst/",
  "aid": "/eɪd/",
  "encourage": "/ɪnˈkɝɹɪdʒ/",
  "implement": "/ˈɪmpləmənt/",
  "monitor": "/ˈmɒnɨtə/",
  "admit": "/ədˈmɪt/",
  "African": "",
  "European": "",
  "Latin": "",
  "Jewish": "",
  "Arabian": "",
  "Portuguese": "",
  "Roman": "/ˈɹəʊmən/",
  "Russian": "",
  "Spanish": "/ˈspæn.ɪʃ/",
  "Swiss": "/swɪs/",
  "Greek": "/ɡɹiːk/",
  "Italian": "",
  "soviet": "/ˈsoʊ.vi.ət/",
  "Indian": "",
  "Australia": "",
  "New Zealand": "/njʉː/",
  "Canada": "",
  "Britain": "",
  "France": "",
  "Germany": "",
  "economy": "",
  "trade": "",
  "market": "",
  "industry": "",
  "merchant": "",
  "financial": "",
  "fund": "",
  "donate": "",
  "endow": "",
  "commercial": "",
  "advertise": "",
  "slogan": "",
  "purchase": "",
  "lease": "",
  "afford": "",
  "retail": "",
  "grocery": "",
  "discount": "",
  "promotion": "",
  "voucher": "",
  "coupon": "",
  "currency": "",
  "exchange": "",
  "swap": "",
  "swop": "",
  "receipt": "",
  "invoice": "",
  "tax": "",
  "levy": "",
  "tariff": "",
  "duty": "",
  "impose": "",
  "consume": "",
  "spend": "",
  "cost": "",
  "expense": "",
  "revenue": "",
  "gross": "",
  "recession": "",
  "depression": "",
  "crisis": "",
  "security": "",
  "bond": "",
  "debt": "",
  "deficit": "/ˈdɛfɪsɪt/",
  "inflation": "/ɪnˈfleɪʃən/",
  "deflation": "/dɪˈfleɪʃən/",
  "dwindle": "/ˈdwɪn.dəl/",
  "decrease": "",
  "downsize": "/ˈdaʊnsaɪz/",
  "decline": "/dɪˈklaɪn/",
  "diminish": "/dɪˈmɪnɪʃ/",
  "reduce": "/ɹɪˈduːs/",
  "increase": "",
  "increment": "/ˈɪŋkɹɪmn̩t/",
  "growth": "/ɡɹoʊθ/",
  "escalate": "/ˈɛs.kə.leɪt/",
  "expand": "/ɛkˈspænd/",
  "influx": "/ˈɪnˌflʌks/",
  "affluent": "/ˈæf.lu.ənt/",
  "enrich": "/ɪnˈɹɪt͡ʃ/",
  "sufficient": "/səˈfɪʃənt/",
  "adequate": "",
  "spare": "/ˈspɛəɹ/",
  "saving": "/ˈseɪvɪŋ/",
  "redundant": "/ɹɪˈdʌn.dənt/",
  "lack": "/læk/",
  "company": "/ˈkʌmp(ə)ni/",
  "firm": "/fɜːm/",
  "enterprise": "",
  "agent": "",
  "entity": "",
  "invest": "",
  "input": "",
  "product": "",
  "acquisition": "",
  "goods": "",
  "cargo": "",
  "insure": "",
  "guarantee": "",
  "reliable": "",
  "negotiation": "",
  "attend": "",
  "absent": "",
  "sale": "",
  "wholesale": "",
  "auction": "",
  "bid": "",
  "deal": "",
  "transaction": "",
  "turnover": "",
  "dump": "",
  "export": "",
  "import": "",
  "quota": "",
  "share": "",
  "benefit": "",
  "interest": "",
  "stock": "",
  "account": "",
  "deposit": "",
  "instalment": "",
  "installment": "",
  "cheque": "",
  "check": "",
  "cash": "",
  "coin": "",
  "shilling": "",
  "copper": "",
  "treasure": "",
  "wealth": "",
  "estate": "",
  "possess": "",
  "legacy": "",
  "descend": "",
  "worthy": "",
  "valuable": "",
  "cheap": "/t͡ʃiːp/",
  "incentive": "/ɪnˈsɛntɪv/",
  "accelerate": "/æk.ˈsɛl.ə.ˌɹeɪt/",
  "prompt": "/pɹɒmpt/",
  "salary": "/ˈsælɚi/",
  "income": "/ˈɪnˌkʌm/",
  "wage": "/weɪd͡ʒ/",
  "payment": "/ˈpeɪmənt/",
  "refund": "",
  "reimburse": "",
  "payroll": "/ˈpeɪɹəʊl/",
  "remuneration": "/ɹə.mjuː.nə.ˈɹeɪ.ʃən/",
  "subsidy": "/ˈsʌbsɨdi/",
  "earn": "/ɝn/",
  "undertaking": "/ˈʌndə(ɹ)ˌteɪkɪŋ/",
  "career": "/kəˈɹɪɹ/",
  "profession": "/pɹəˈfɛʃən/",
  "occupation": "/ɑkjəˈpeɪʃən/",
  "job": "/d͡ʒɒb/",
  "vocation": "/voʊˈkeɪʃən/",
  "labour": "/ˈleɪ.bə/",
  "labor": "/ˈleɪ.bɚ/",
  "workforce": "",
  "workaholic": "",
  "personnel": "/pɝ.səˈnɛl/",
  "clerk": "/klɝk/",
  "interview": "/ˈɪntɚvjuː/",
  "résumé": "",
  "resume": "/ɹəˈzjuːm/",
  "recommend": "/ɹɛkəˈmɛnd/",
  "employ": "/ɛmˈplɔɪ/",
  "hire": "/haɪɹ/",
  "fire": "/ˈfaɪɚ/",
  "lay-off": "/leɪ/ /ɔːf/",
  "dismiss": "/dɪsˈmɪs/",
  "discharge": "/ˈdɪstʃɑːdʒ/",
  "resign": "/ɹɪˈzaɪn/",
  "sack": "/sæk/",
  "retire": "/ɹəˈtaɪə(ɹ)/",
  "result": "/ɹɪˈzʌlt/",
  "failure": "/ˈfeɪl.jɚ/",
  "abortion": "",
  "loss": "",
  "opportunity": "",
  "chance": "",
  "choose": "",
  "change": "",
  "solve": "",
  "develop": "",
  "sustainable": "",
  "improve": "",
  "manage": "",
  "regulate": "",
  "sanction": "",
  "coordinate": "",
  "cooperate": "",
  "collaborate": "",
  "law": "",
  "legal": "",
  "rule": "",
  "regulation": "",
  "treaty": "",
  "agreement": "",
  "charter": "",
  "protocol": "",
  "norm": "",
  "benchmark": "",
  "criteria": "",
  "standard": "",
  "allow": "",
  "admission": "",
  "enforce": "",
  "default": "",
  "reject": "",
  "constraint": "",
  "official": "",
  "mandatory": "",
  "potent": "",
  "bound": "",
  "obligation": "",
  "court": "",
  "supreme": "",
  "enact": "",
  "legislate": "",
  "equity": "",
  "fair": "",
  "just": "",
  "prejudice": "",
  "discrimination": "",
  "accuse": "",
  "sue": "/suː/",
  "prosecute": "/ˈpɹɒsɪkjuːt/",
  "condemn": "/kənˈdɛm/",
  "complain": "/kəmˈpleɪn/",
  "boycott": "/ˈbɔɪkɒt/",
  "session": "/ˈsɛʃən/",
  "mediate": "/ˈmidi.ət/",
  "plea": "/pliː/",
  "appeal": "/əˈpiːl/",
  "contradict": "/kɒntɹəˈdɪkt/",
  "persuade": "/pɚˈsweɪd/",
  "controversy": "/kənˈtɹɒvəsi/",
  "whisper": "/ˈ(h)wɪspɚ/",
  "mutter": "/ˈmʌtɚ/",
  "murmur": "/ˈmɝ.mɚ/",
  "silent": "/ˈsaɪlənt/",
  "mute": "/mjuːt/",
  "investigate": "[ɪn.ˈves.tɪ.ɡeɪ̯t]",
  "witness": "/ˈwɪtnəs/",
  "justify": "/ˈdʒʌstɪfaɪ/",
  "reasonable": "/ˈɹiː.zən.ə.bəl/",
  "suitable": "/ˈsuːtəbl/",
  "judge": "/d͡ʒʌd͡ʒ/",
  "jury": "/ˈd͡ʒʊə.ɹi/",
  "trial": "/ˈtɹaɪəl/",
  "suspect": "/ˈsʌs.pɛkt/",
  "sentence": "[ˈsɛntn̩t͡s]",
  "arrest": "/əˈɹɛst/",
  "jail": "/dʒeɪl/",
  "prison": "/ˈpɹɪzən/",
  "confine": "/ˈkɒnfaɪn/",
  "oversee": "/əʊvə(ɹ)siː/",
  "supervise": "",
  "restrict": "/ɹɪˈstɹɪkt/",
  "restrain": "",
  "commit": "",
  "sin": "",
  "crime": "",
  "vice": "",
  "bribe": "",
  "rob": "",
  "pirate": "",
  "steal": "",
  "thief": "",
  "murder": "",
  "suicide": "",
  "deceive": "",
  "cheat": "",
  "fraud": "",
  "liar": "",
  "trap": "",
  "trick": "",
  "pretend": "",
  "fool": "",
  "stigma": "",
  "confess": "",
  "conform": "",
  "reconcile": "",
  "obey": "",
  "succumb": "",
  "penalty": "",
  "fine": "",
  "mortgage": "/ˈmɔɹ.ɡɪdʒ/",
  "ownership": "",
  "copyright": "/ˈkɑpiˌɹaɪt/",
  "privilege": "/ˈpɹɪv(ɪ)lɪdʒ/",
  "accredit": "/ə.ˈkɹɛd.ɪt/",
  "clue": "/kluː/",
  "access": "/ˈækˌsɛs/",
  "anonymous": "/əˈnɒnəməs/",
  "false": "/fɒls/",
  "genuine": "/ˈdʒɛnjuːˌaɪn/",
  "procedure": "/pɹəˈsidʒɚ/",
  "routine": "/ɹuːˈtiːn/",
  "consequence": "/ˈkɑnsɪkwəns/",
  "demand": "/dəˈmænd/",
  "request": "/ɹɪˈkwɛst/",
  "require": "/ɹɪˈkwaɪɹ/",
  "petition": "/pəˈtɪ.ʃən/",
  "command": "/kəˈmænd/",
  "instruct": "/ˌɪnˈstɹʌkt/",
  "violence": "/ˈvaɪləns/",
  "conflict": "/kənˈflɪkt/",
  "raid": "/ɹeɪd/",
  "enormity": "/ɪˈnɔːmɪti/",
  "campaign": "/kæmˈpeɪn/",
  "battle": "/ˈbætl̩/",
  "struggle": "/ˈstrʌɡəl/",
  "explosion": "/ɛkˈsploʊ.ʒən/",
  "bombard": "/bəmˈbɑɹd/",
  "bomb": "/bɒm/",
  "blast": "",
  "burst": "",
  "spark": "",
  "twinkle": "",
  "gunpowder": "",
  "tank": "",
  "cannon": "",
  "missile": "",
  "weapon": "",
  "pistol": "",
  "rifle": "",
  "bullet": "",
  "target": "",
  "deflect": "",
  "mission": "",
  "flame": "",
  "flare": "",
  "glitter": "",
  "glow": "",
  "blade": "",
  "sword": "",
  "ax": "",
  "hammer": "",
  "arrow": "",
  "spear": "",
  "helmet": "",
  "shield": "",
  "equip": "",
  "prepare": "",
  "provide": "",
  "deploy": "",
  "hit": "",
  "beat": "",
  "strike": "",
  "punch": "",
  "chop": "",
  "stab": "",
  "dilemma": "",
  "plight": "",
  "pitfall": "",
  "conspiracy": "",
  "destitute": "",
  "famine": "",
  "starve": "",
  "deprive": "",
  "seize": "",
  "pursue": "",
  "threat": "/θɹɛt/",
  "offend": "/əˈfɛnd/",
  "aggressive": "/əˈɡɹɛs.ɪv/",
  "invade": "/ɪnˈveɪd/",
  "trespass": "/ˈtɹɛspəs/",
  "intrude": "/ɪnˈtɹuːd/",
  "violate": "/ˈvaɪəˌleɪt/",
  "attack": "/əˈtæk/",
  "assault": "/əˈsɔːlt/",
  "challenge": "/ˈtʃæl.əndʒ/",
  "siege": "/siːdʒ/",
  "surround": "/səˈɹaʊnd/",
  "enclose": "/ənˈkloʊz/",
  "pause": "/pɔz/",
  "halt": "/hɔːlt/",
  "cease": "/siːs/",
  "oppose": "/əˈpoʊz/",
  "oppress": "/əˈpɹɛs/",
  "counter": "/ˈkaʊntə/",
  "deter": "/dɪˈtɜː(ɹ)/",
  "forbid": "/fɚˈbɪd/",
  "prohibit": "/pɹoʊˈhɪbɪt/",
  "prevent": "/pɹəˈvɛnt/",
  "revolt": "/ɹɪˈvoʊlt/",
  "betray": "/bəˈtɹeɪ/",
  "treason": "/ˈtɹiː.zən/",
  "rebel": "/ˈɹɛbəl/",
  "traitor": "/ˈtɹeɪtɚ/",
  "patriot": "/ˈpeɪ.tɹi.ət/",
  "blame": "/bleɪm/",
  "reproach": "/ɹɪˈpɹoʊtʃ/",
  "evidence": "[ˈɛvəɾəns]",
  "proof": "",
  "terror": "",
  "terrible": "",
  "terrific": "",
  "horrible": "",
  "alarm": "",
  "dread": "",
  "frighten": "",
  "tension": "",
  "turbulent": "",
  "turmoil": "",
  "scenario": "",
  "occasion": "",
  "limit": "",
  "boundary": "",
  "rein": "",
  "compete": "",
  "contest": "",
  "contend": "",
  "rival": "",
  "competitor": "",
  "enemy": "",
  "strategy": "",
  "tactic": "",
  "maneuver": "",
  "manoeuvre": "",
  "blueprint": "",
  "warn": "",
  "compel": "",
  "oblige": "",
  "protest": "",
  "refute": "",
  "might": "",
  "force": "",
  "reinforce": "",
  "impair": "",
  "mitigate": "",
  "comfort": "",
  "event": "",
  "matter": "",
  "happen": "",
  "occur": "",
  "savage": "",
  "reckless": "",
  "fierce": "/fɪɹs/",
  "foul": "/faʊl/",
  "evil": "/ˈivəl/",
  "devil": "/ˈdɛvəl/",
  "punishment": "/ˈpʌnɪʃmənt/",
  "execute": "/ˈɛksɪˌkjuːt/",
  "hang": "[heɪŋ]",
  "sacrifice": "/ˈsækɹɪfaɪs/",
  "casualty": "/ˈkaʒ(ʊ)əlti/",
  "bury": "/ˈbɛ.ɹi/",
  "funeral": "/ˈfjunəɹəl/",
  "grave": "/ɡɹeɪv/",
  "tomb": "/tum/",
  "hell": "",
  "maritime": "/ˈmæ.ɹɪˌtaɪm/",
  "naval": "/ˈneɪvəl/",
  "fleet": "/flit/",
  "troop": "/tɹuːp/",
  "landing": "/ˈlændɪŋ/",
  "hover": "/ˈhʌ.vɚ/",
  "proceed": "/pɹəˈsiːd/",
  "progress": "/ˈpɹɒɡɹɛs/",
  "military": "/ˈmɪl.ɪ.tɛɹ.i/",
  "nuclear": "/ˈn(j)ukliɚ/",
  "poison": "/ˈpɔɪz(ə)n/",
  "devastate": "/ˈdɛvəsteɪt/",
  "risk": "/ɹɪsk/",
  "adventure": "/ædˈvɛnt͡ʃɚ/",
  "peril": "/ˈpɛɹəl/",
  "catastrophe": "/kəˈtæstɹəfi/",
  "collapse": "/kəˈlæps/",
  "torture": "/ˈtɔɹt͡ʃɚ/",
  "humiliate": "/hjuːˈmɪliˌeɪt/",
  "damage": "",
  "harmful": "",
  "mislead": "",
  "disturb": "",
  "interfere": "",
  "interrupt": "",
  "retreat": "",
  "shrink": "",
  "withdraw": "",
  "withstand": "",
  "compromise": "",
  "surrender": "",
  "escape": "",
  "avoid": "",
  "quit": "",
  "abandon": "",
  "forgo": "",
  "forego": "",
  "discard": "/ˈdɪskɑːd/",
  "rid": "",
  "defend": "/diˈfɛnd/",
  "safeguard": "",
  "defeat": "/dɪˈfiːt/",
  "resist": "/ɹəˈzɪst/",
  "capture": "/ˈkæp.t͡ʃɚ/",
  "victory": "/ˈvɪkt(ə)ɹi/",
  "triumph": "/ˈtɹaɪ.əmf/",
  "conquer": "/ˈkɑŋkɚ/",
  "monument": "/ˈmɑnjəmənt/",
  "tablet": "/ˈtæblət/",
  "statue": "/ˈstætʃu/",
  "medal": "[ˈmɛd.ɫ̩]",
  "honor": "/ˈɑn.ɚ/",
  "honour": "/ˈɒnə(ɹ)/",
  "glorious": "/ˈɡlɔɹ.i.əs/",
  "contribute": "/kənˈt(ʃ)ɹɪb.jut/",
  "devote": "/dɪˈvoʊt/",
  "owe": "/oʊ/",
  "patrol": "/pəˈtɹəʊl/",
  "guard": "/ɡɑɹd/",
  "camouflage": "/ˈkæ.məˌflɑːʒ/",
  "obstacle": "/ˈɑbstəkl̩/",
  "burrow": "/ˈbɜɹoʊ/",
  "spy": "/spaɪ/",
  "scout": "[skʌʊt]",
  "general": "/ˈd͡ʒɛnəɹəl/",
  "soldier": "/ˈsɒld͡ʒə/",
  "veteran": "",
  "pioneer": "",
  "prophet": "",
  "herald": "",
  "heir": "",
  "successor": "",
  "generation": "",
  "surname": "",
  "gender": "",
  "sex": "",
  "female": "",
  "couple": "",
  "spouse": "",
  "husband": "",
  "gay": "",
  "grandfather": "",
  "father-in-law": "",
  "sibling": "",
  "cousin": "",
  "nephew": "",
  "niece": "",
  "twin": "",
  "embryo": "",
  "infant": "",
  "orphan": "",
  "juvenile": "",
  "youngster": "",
  "youth": "",
  "gang": "",
  "teenager": "",
  "adolescence": "",
  "kin": "",
  "folk": "",
  "relative": "",
  "intimate": "",
  "dear": "",
  "darling": "",
  "lover": "",
  "beloved": "",
  "madam": "",
  "hostess": "",
  "landlady": "/ˈlændˌleɪ.di/",
  "mistress": "/ˈmɪstɹɪs/",
  "housewife": "",
  "widow": "/ˈwɪ.doʊ/",
  "maid": "/meɪd/",
  "maiden": "/ˈmeɪdən/",
  "household": "/ˈhaʊshoʊld/",
  "chore": "/tʃɔː/",
  "host": "/hoʊst/",
  "landlord": "/ˈlænd.lɔːd/",
  "tenant": "/ˈtɛ.nənt/",
  "guest": "/ɡɛst/",
  "customer": "/ˈkʌstəmə/",
  "client": "/ˈklaɪ.ənt/",
  "encounter": "/ɪnˈkaʊntɚ/",
  "chase": "/tʃeɪs/",
  "miss": "/mɪs/",
  "appointment": "/əˈpɔɪnt.mɛnt/",
  "accompany": "/ə.ˈkʌm.pə.ni/",
  "dependent": "/dɪˈpɛndənt/",
  "propose": "/pɹəˈpoʊz/",
  "engagement": "/ɪnˈɡeɪd͡ʒ.mənt/",
  "marry": "/ˈmeɹi/",
  "wedding": "/ˈwɛdɪŋ/",
  "honeymoon": "/ˈhʌn.iˌmun/",
  "kiss": "",
  "divorce": "",
  "separate": "",
  "single": "",
  "sole": "",
  "respective": "",
  "each": "",
  "individual": "",
  "commuter": "",
  "neighborhood": "",
  "neighbourhood": "",
  "member": "",
  "boss": "",
  "manager": "",
  "supervisor": "",
  "subordinate": "",
  "partner": "",
  "colleague": "",
  "comrade": "",
  "acquaintance": "",
  "friendship": "",
  "affection": "",
  "stranger": "",
  "apprentice": "",
  "deputy": "",
  "hero": "",
  "heroine": "",
  "actress": "",
  "chancellor": "",
  "commander": "",
  "director": "",
  "proponent": "",
  "committee": "",
  "council": "",
  "delegate": "",
  "specialist": "",
  "consultant": "",
  "veterinary": "",
  "counsellor": "",
  "counselor": "",
  "solicitor": "",
  "attorney": "",
  "umpire": "",
  "cashier": "",
  "fireman": "",
  "nurse": "",
  "gardener": "",
  "barber": "/ˈbɑɹ.bɚ/",
  "haircut": "",
  "fisherman": "/ˈfɪʃəmən/",
  "butcher": "/ˈbʊt͡ʃ.ɚ/",
  "groom": "/ɡɹuːm/",
  "hostage": "/ˈhɑstɪdʒ/",
  "toil": "/tɔɪl/",
  "beggar": "/ˈbɛɡɚ/",
  "slave": "/sleɪv/",
  "coward": "/ˈkaʊəd/",
  "act": "/æk/",
  "behave": "/bəˈheɪv/",
  "deed": "/diːd/",
  "accustom": "",
  "react": "/ɹiːˈækt/",
  "respond": "",
  "reflect": "/ɹɪˈflɛkt/",
  "adopt": "/əˈdɑpt/",
  "nourish": "/ˈnɝ.ɪʃ/",
  "mow": "/moʊ/",
  "support": "/səˈpɔɹt/",
  "exhale": "/ɛksˈheɪl/",
  "intake": "/ˈɪnteɪk/",
  "revive": "/ɹɪˈvaɪv/",
  "survive": "/sɚˈvaɪv/",
  "glare": "/ɡlɛə/",
  "glimpse": "/ɡlɪmps/",
  "glance": "/ɡlæns/",
  "peep": "/pip/",
  "gaze": "",
  "peer": "",
  "stare": "",
  "contemplate": "",
  "vow": "",
  "oath": "",
  "pledge": "",
  "whistle": "",
  "reply": "",
  "notify": "",
  "assert": "",
  "explain": "",
  "quarrel": "",
  "dispute": "",
  "argument": "",
  "mention": "",
  "hurry": "",
  "hasten": "",
  "urge": "",
  "scold": "",
  "curse": "",
  "swear": "",
  "provoke": "",
  "preach": "",
  "boast": "",
  "tease": "",
  "mock": "",
  "touch": "",
  "hug": "",
  "clap": "",
  "applaud": "",
  "kneel": "",
  "catch": "",
  "snatch": "",
  "grab": "",
  "grasp": "",
  "overtake": "",
  "follow": "",
  "grip": "",
  "mess": "",
  "twist": "",
  "scatter": "",
  "fold": "",
  "fasten": "",
  "loosen": "/ˈluːsn̩/",
  "smash": "/smæʃ/",
  "scratch": "",
  "wipe": "/waɪp/",
  "scrape": "/skɹeɪp/",
  "polish": "/ˈpɑlɪʃ/",
  "split": "/splɪt/",
  "sway": "/sweɪ/",
  "shake": "/ˈʃeɪk/",
  "vibrate": "/ˈvaɪ.bɹeɪt/",
  "whirl": "/wɝl/",
  "rotate": "/ˈɹoʊteɪt/",
  "shuffle": "/ˈʃʌfəl/",
  "collide": "/kəˈlɑɪd/",
  "contact": "",
  "connect": "/kəˈnɛkt/",
  "combine": "/kəmˈbaɪn/",
  "integrate": "/ˈɪntəɡɹeɪt/",
  "penetrate": "/ˈpɛnɪtɹeɪt/",
  "pierce": "/pɪɹs/",
  "insert": "/ɪnˈsɜːt/",
  "tilt": "/tɪlt/",
  "tow": "",
  "trail": "/tɹeɪl/",
  "arrange": "/əˈɹeɪndʒ/",
  "manipulate": "/məˈnɪpjʊleɪt/",
  "steer": "/stɪə(ɹ)/",
  "baptize": "/ˈbæptaɪz/",
  "baptise": "",
  "bet": "/ˈbɛt/",
  "stake": "/steɪk/",
  "gamble": "/ˈɡæm.bəl/",
  "promise": "/ˈpɹɑmɪs/",
  "attract": "",
  "obsess": "",
  "mesmerize": "",
  "mesmerise": "",
  "nightmare": "",
  "amaze": "",
  "marvel": "",
  "astonish": "",
  "involve": "",
  "annoy": "",
  "upset": "",
  "bewilder": "",
  "irony": "",
  "indignity": "",
  "contempt": "",
  "neglect": "",
  "disregard": "",
  "ignorance": "",
  "bias": "",
  "deviate": "",
  "expel": "",
  "flee": "",
  "bully": "",
  "panic": "",
  "terrify": "",
  "revenge": "",
  "kidnap": "",
  "hijack": "",
  "smuggle": "",
  "convict": "",
  "strangle": "",
  "massacre": "",
  "decimation": "",
  "intervene": "",
  "impede": "",
  "allure": "",
  "bait": "",
  "induce": "",
  "tempt": "",
  "designate": "",
  "assign": "/əˈsaɪn/",
  "distribute": "",
  "despatch": "/dəˈspætʃ/",
  "dispatch": "/dɪˈspætʃ/",
  "detach": "/dɪˈtætʃ/",
  "undo": "",
  "disguise": "/dɪsˈɡaɪz/",
  "conceal": "/kənˈsiːl/",
  "refuse": "/ˈɹɛfjuːs/",
  "exclude": "",
  "reverse": "/ɹɪˈvɜːs/",
  "assure": "/əˈʃɝ/",
  "undertake": "/ʌndəˈteɪk/",
  "stipulate": "/ˈstɪpjuˌleɪt/",
  "convince": "",
  "reassure": "/ɹiəˈʃʊə(ɹ)/",
  "wish": "/wɪʃ/",
  "aspire": "",
  "desire": "/diˈzaɪɚ/",
  "yearn": "/jɝn/",
  "invoke": "/ɪnˈvoʊk/",
  "itch": "/ɪt͡ʃ/",
  "attempt": "/əˈtɛmpt/",
  "strive": "",
  "effort": "/ˈɛfɚt/",
  "fulfil": "",
  "fulfill": "/fəˈfɪl/",
  "sort": "/sɔːt/",
  "loom": "/lum/",
  "launch": "",
  "commence": "/kəˈmɛns/",
  "exploit": "",
  "explore": "/ɪkˈsplɔɹ/",
  "exert": "",
  "tackle": "",
  "cope": "",
  "dispose": "",
  "conduct": "",
  "omit": "",
  "delete": "",
  "cancel": "",
  "clear": "",
  "erase": "",
  "rescue": "",
  "resort": "",
  "recover": "",
  "restore": "",
  "rectify": "",
  "redeem": "",
  "offset": "",
  "replenish": "",
  "obtain": "",
  "gain": "",
  "supply": "",
  "offer": "",
  "render": "",
  "enlarge": "",
  "augment": "",
  "magnify": "",
  "amplify": "",
  "exaggerate": "",
  "prolong": "",
  "uphold": "",
  "backup": "",
  "propel": "",
  "update": "",
  "raise": "",
  "leak": "",
  "spill": "",
  "seep": "",
  "ooze": "/uːz/",
  "evacuate": "",
  "trench": "/tɹɛntʃ/",
  "saturate": "/ˈsætʃəˌɹeɪt/",
  "excuse": "",
  "forgive": "/fɚˈɡɪv/",
  "contain": "/kənˈteɪn/",
  "regard": "/ɹɪˈɡɑɹd/",
  "flatter": "/ˈflætɚ/",
  "worship": "/ˈwɝʃɪp/",
  "cause": "",
  "sake": "/seɪk/",
  "purpose": "",
  "objective": "/əbˈd͡ʒɛk.tɪv/",
  "arouse": "",
  "trigger": "/ˈtɹɪɡə/",
  "seek": "/siːk/",
  "retrieve": "/ɹiˈtɹiv/",
  "testify": "",
  "verify": "",
  "specify": "/ˈspɛsɪfaɪ/",
  "enlighten": "/ənˈlaɪtn̩/",
  "impart": "/ɪmˈpɑːɹt/",
  "deserve": "/dɪˈzɝv/",
  "drop": "/dɹɑp/",
  "sink": "",
  "plummet": "/ˈplʌm.ət/",
  "muffle": "/mʌfl̩/",
  "overshadow": "/ˌoʊ.vɚˈʃæd.oʊ/",
  "invite": "",
  "welcome": "/ˈwɛlkəm/",
  "greet": "/ɡɹiːt/",
  "salute": "/səˈl(j)uːt/",
  "celebrate": "/ˈsɛl.ə.bɹeɪt/",
  "congratulate": "/-t͡ʃə-/",
  "bless": "/blɛs/",
  "participate": "/pɑːˈtɪsɪpeɪt/",
  "farewell": "",
  "assort": "/əˈsɔɹt/",
  "correspond": "/ˌkɑɹəˈspɑnd/",
  "accord": "/ə.ˈkɔɹd/",
  "attribute": "",
  "recall": "",
  "recollect": "/ɹɛkəˈlɛkt/",
  "remind": "",
  "retell": "",
  "repeat": "",
  "retrospect": "",
  "impress": "",
  "surmount": "",
  "mortify": "",
  "pervade": "",
  "replace": "",
  "substitute": "",
  "distinguish": "",
  "differentiate": "",
  "incline": "",
  "lean": "",
  "sideways": "",
  "feel": "",
  "mood": "",
  "emotion": "",
  "temper": "",
  "manner": "",
  "attitude": "",
  "character": "",
  "personality": "",
  "trait": "",
  "virtue": "",
  "feature": "",
  "stature": "",
  "flesh": "",
  "mankind": "",
  "human": "",
  "bone": "",
  "backbone": "",
  "skeleton": "",
  "skull": "",
  "brain": "",
  "mind": "",
  "physical": "",
  "mental": "",
  "cheek": "",
  "forehead": "",
  "brow": "",
  "eyelash": "",
  "lip": "/lɪp/",
  "mouth": "/maʊθ/",
  "tongue": "/tɒŋɡ/",
  "throat": "/ˈθɹoʊt/",
  "gorge": "",
  "chin": "/tʃɪn/",
  "jaw": "/d͡ʒɑ/",
  "neck": "/nɛk/",
  "beard": "",
  "shoulder": "/ˈʃoʊldɚ/",
  "limb": "/lɪm/",
  "elbow": "/ˈɛl.boʊ/",
  "wrist": "/ɹɪst/",
  "thumb": "/θʌm/",
  "palm": "/pɑlm/",
  "finger": "/ˈfɪŋɡɚ/",
  "fist": "/fɪst/",
  "chest": "/t͡ʃɛst/",
  "abdomen": "/æbˈdoʊ.mən/",
  "rib": "/ɹɪb/",
  "waist": "/weɪst/",
  "organ": "/ˈɔɹ.ɡən/",
  "liver": "/ˈlɪvɚ/",
  "stomach": "/ˈstʌmək/",
  "womb": "/wuːm/",
  "kidney": "/ˈkɪdni/",
  "lung": "/ˈlʌŋ/",
  "gland": "",
  "chamber": "",
  "intestine": "",
  "thigh": "",
  "joint": "",
  "knee": "",
  "lap": "",
  "ankle": "",
  "heel": "",
  "toe": "",
  "muscle": "",
  "pore": "",
  "pulse": "",
  "artery": "",
  "nerve": "",
  "hormone": "",
  "immune": "",
  "stimulus": "",
  "biorhythm": "",
  "lifestyle": "",
  "habit": "",
  "sense": "",
  "sight": "",
  "eyesight": "",
  "view": "",
  "visual": "",
  "visible": "",
  "vague": "",
  "blind": "",
  "dumb": "",
  "aural": "",
  "dental": "",
  "awake": "",
  "yawn": "",
  "nap": "",
  "doze": "",
  "quiet": "",
  "asleep": "",
  "cripple": "",
  "lame": "",
  "dwarf": "/dwɔɹf/",
  "pregnancy": "",
  "born": "/ˈbɔɹn/",
  "condom": "/ˈkɑn.dəm/",
  "clone": "/kloʊn/",
  "symptom": "/ˈsɪm(p)təm/",
  "disease": "/dɪˈziz/",
  "illness": "/ˈɪl.nəs/",
  "moan": "/moʊn/",
  "infection": "/ɪnˈfɛkʃən/",
  "detriment": "/ˈdɛtɹɪmənt/",
  "broken": "/ˈbɹəʊkən/",
  "disable": "",
  "invalid": "/ɪnˈvæl.ɪd/",
  "patient": "",
  "dysfunction": "/dɪsˈfʌŋk.ʃən/",
  "diabetes": "",
  "obesity": "",
  "overweight": "",
  "hypertension": "",
  "paralyse": "",
  "paralyze": "",
  "dizzy": "/ˈdɪzi/",
  "insane": "/ɪnˈseɪn/",
  "insomnia": "/ɪnˈsɒmniə/",
  "allergy": "[ˈæl.ə.dʒi]",
  "heart attack": "/əˈtæk/",
  "cancer": "/ˈkænsə/",
  "arthritis": "",
  "pimple": "/ˈpɪmp(ə)l/",
  "stroke": "/stɹoʊk/",
  "plague": "/pleɪɡ/",
  "flu": "",
  "influenze": "",
  "fever": "",
  "headache": "/ˈhɛdeɪk/",
  "swell": "/swɛl/",
  "choke": "/t͡ʃəʊk/",
  "injure": "/ˈɪndʒɚ/",
  "injury": "",
  "hurt": "/hɝt/",
  "bleed": "/ˈbliːd/",
  "bruise": "/bɹuːz/",
  "scar": "/skɑː(ɹ)/",
  "wound": "/wund/",
  "trauma": "/ˈtɹaʊ.mə/",
  "lump": "/lʌmp/",
  "pain": "/peɪn/",
  "death": "",
  "mortal": "/ˈmɔːtəl/",
  "demise": "/dɪˈmaɪz/",
  "doom": "/duːm/",
  "fatal": "",
  "lethal": "/ˈliː.θəl/",
  "corpus": "/ˈkɔːpəs/",
  "overwork": "/ˌəʊvəˈwɜːk/",
  "exhaust": "/ɪɡˈzɔːst/",
  "fatigue": "",
  "faint": "/feɪnt/",
  "feeble": "/ˈfiːbəl/",
  "weary": "/ˈwɪəɹi/",
  "weaken": "",
  "uncomfortable": "",
  "unconscious": "",
  "chronic": "",
  "acute": "",
  "sore": "",
  "sorrow": "",
  "suffering": "",
  "lament": "",
  "hospital": "",
  "therapy": "",
  "health care": "",
  "sanitary": "",
  "medical": "",
  "curative": "",
  "hygiene": "",
  "fitness": "",
  "clinic": "",
  "physician": "",
  "surgeon": "",
  "operation": "",
  "cure": "",
  "heal": "",
  "treatment": "",
  "prescription": "",
  "transplant": "",
  "X-ray": "",
  "injection": "",
  "precaution": "",
  "vaccinate": "",
  "quarantine": "",
  "segregate": "",
  "isolate": "",
  "pharmacy": "",
  "medicine": "",
  "remedy": "",
  "drug": "",
  "pill": "",
  "antibiotic": "",
  "acupuncture": "",
  "penicillin": "",
  "morphine": "",
  "dose": "",
  "recovery": "/ɹəˈkʌvəɹi/",
  "refresh": "/ɹɪˈfɹɛʃ/",
  "relief": "/ɹɪˈliːf/",
  "relieve": "/ɹɪˈliːv/",
  "alleviate": "",
  "ease": "/iz/",
  "relax": "/ɹɪˈlæks/",
  "normal": "/ˈnɔɹməl/",
  "common": "/ˈkɑmən/",
  "usual": "/ˈjuːʒʊəl/",
  "optimistic": "/ˌɒptɪˈmɪstɪk/",
  "pessimistic": "/ˌpɛ.səˈmɪs.tɪk/",
  "positive": "/ˈpɑzɪ̈tɪv/",
  "negative": "",
  "passive": "/ˈpæs.ɪv/",
  "enthusiastic": "/ɪnˌθjuːzɪˈæstɪk/",
  "indifferent": "/ɪnˈdɪf.ə.ɹənt/",
  "apathetic": "/æp.əˈθɛt.ɪk/",
  "negligible": "/ˈnɛɡlɪdʒɪbəl/",
  "happiness": "/ˈhæpinəs/",
  "delight": "",
  "merry": "/ˈmeɪɹi/",
  "fun": "/fʌn/",
  "joke": "",
  "laughter": "/ˈlæftɚ/",
  "joy": "",
  "please": "",
  "rejoice": "",
  "thrill": "",
  "cheer": "",
  "pleasure": "",
  "agreeable": "",
  "exhilarate": "",
  "satisfactory": "",
  "desirable": "",
  "exciting": "",
  "keen": "",
  "zeal": "",
  "lively": "",
  "lovely": "",
  "fond": "",
  "favor": "",
  "favour": "",
  "surprising": "",
  "startle": "",
  "amazing": "",
  "astound": "",
  "hectic": "",
  "liberal": "",
  "generous": "",
  "gentle": "",
  "humble": "",
  "modest": "",
  "humorous": "",
  "polite": "",
  "frank": "",
  "mysterious": "",
  "curious": "",
  "daring": "",
  "manly": "",
  "direct": "",
  "earnest": "",
  "honesty": "",
  "proud": "",
  "seriously": "",
  "friendly": "",
  "hospitable": "/hɒsˈpɪtəbl̩/",
  "romantic": "/ɹoʊˈmæn(t)ɪk/",
  "freedom": "/ˈfɹiːdəm/",
  "careful": "",
  "concern": "/kənˈsɝn/",
  "confidence": "/ˈkɒnfɪdəns/",
  "considerate": "/kənˈsɪdəɹət/",
  "thoughtful": "",
  "sympathetic": "/ˌsɪmpəˈθɛtɪk/",
  "ready": "/ˈɹɛdi/",
  "apologize": "/əˈpɑləd͡ʒaɪz/",
  "apologise": "/əˈpɒləˌdʒaɪz/",
  "apology": "/əˈpɒl.ə.dʒi/",
  "mercy": "",
  "admire": "/ədˈmaɪɹ/",
  "remarkable": "/ɹɪˈmɑɹkəbl̩/",
  "grateful": "/ˈɡɹeɪtfəl/",
  "gratitude": "/ˈɡɹætɪt(j)ud/",
  "eager": "/ˈiɡɚ/",
  "sound": "",
  "picturesque": "/pɪktʃəˈɹɛsk/",
  "promising": "/ˈpɹɒmɪsɪŋ/",
  "prominent": "/ˈpɹɑmɪnənt/",
  "awesome": "/ˈɔs.əm/",
  "arduous": "/ˈɑːɹd͡ʒuəs/",
  "tough": "",
  "robust": "",
  "sturdy": "",
  "steadfast": "",
  "tender": "",
  "temperate": "",
  "delicate": "",
  "mundane": "",
  "naive": "",
  "childish": "",
  "sincere": "",
  "liable": "",
  "trustworthy": "",
  "enterprising": "",
  "sane": "",
  "strenuous": "",
  "rigorous": "",
  "strict": "",
  "severe": "",
  "mutual": "",
  "resemble": "",
  "similar": "",
  "familiar": "",
  "naked": "",
  "bare": "",
  "private": "",
  "intuition": "",
  "spontaneous": "",
  "implicit": "",
  "illusion": "",
  "imaginary": "",
  "fancy": "",
  "fate": "",
  "fortune": "",
  "agony": "",
  "grief": "",
  "grieve": "",
  "miserable": "",
  "distress": "",
  "sadness": "/ˈsædnəs/",
  "gloomy": "",
  "disappoint": "/dɪsəˈpɔɪnt/",
  "discourage": "/dɪsˈkɝɪd͡ʒ/",
  "wretched": "/ˈɹɛtʃɪd/",
  "frustrating": "/fɹʌˈstɹeɪ̯tɪŋ/",
  "mourn": "/mɔːn/",
  "anger": "/ˈæŋɡɚ/",
  "furious": "/ˈfjɝ.i.əs/",
  "frown": "/fɹaʊn/",
  "rage": "/ɹeɪdʒ/",
  "irritate": "/ˈɪɹɪteɪt/",
  "hate": "/heɪt/",
  "hatred": "/ˈheɪtɹɪd/",
  "nuisance": "/ˈn(j)uːsəns/",
  "disgust": "/dɪsˈɡʌst/",
  "vex": "/vɛks/",
  "harass": "/həˈɹæs/",
  "bore": "/bɔɹ/",
  "bother": "[ˈbɒðə(ɹ)]",
  "troublesome": "/ˈtɹʌbl̩səm/",
  "awful": "/ˈɔfəl/",
  "unpleasant": "/ʌnˈplezənt/",
  "adverse": "/ədˈvɜ(ɹ)s/",
  "hostile": "/ˈhɑstaɪl/",
  "indignant": "/ɪnˈdɪɡ.nənt/",
  "radical": "/ˈɹædɪkəl/",
  "mad": "/ˈmæd/",
  "crazy": "/ˈkɹeɪzi/",
  "wicked": "",
  "vicious": "",
  "vulgar": "",
  "ego": "",
  "selfish": "",
  "nasty": "",
  "rash": "",
  "volatile": "",
  "weird": "",
  "excessive": "",
  "anxiety": "",
  "restless": "",
  "uneasy": "",
  "fear": "",
  "timid": "",
  "fuss": "",
  "insult": "",
  "unkind": "",
  "envy": "",
  "jealous": "",
  "doubt": "",
  "suspicion": "",
  "skeptical": "",
  "sceptical": "",
  "unsatisfactory": "",
  "unstable": "",
  "unsuitable": "",
  "unwilling": "",
  "reluctant": "",
  "hesitate": "",
  "confuse": "",
  "guilty": "",
  "embarrass": "",
  "regret": "",
  "repent": "",
  "ashamed": "",
  "sigh": "",
  "weep": "",
  "tolerance": "",
  "ignorant": "",
  "endure": "",
  "sly": "",
  "cunning": "",
  "arbitrary": "",
  "ridiculous": "",
  "stupid": "",
  "awkward": "",
  "clumsy": "",
  "careless": "/ˈkɛɹləs/",
  "oblivious": "/əˈblɪ.vi.əs/",
  "naughty": "/ˈnɔːti/",
  "greedy": "/ˈɡɹiːdi/",
  "obtrusive": "/əbˈtɹuːsɪv/",
  "slothful": "",
  "sluggish": "/ˈslʌɡɪʃ/",
  "impulse": "/ˈɪmpʌls/",
  "rigid": "/ˈɹɪdʒɪd/",
  "stubborn": "/ˈstʌbən/",
  "stereotype": "/ˈstɛ.ɹi.əˌtaɪp/",
  "daily": "/ˈdeɪli/",
  "monthly": "/ˈmʌnθli/",
  "quarterly": "",
  "annual": "/ˈæn.ju.əl/",
  "yearly": "/ˈjɪɹli/",
  "anniversary": "/ˌænɪˈvɜːs(ə)ɹi/",
  "era": "/ˈɪə̯ɹ.ə/",
  "present": "/ˈpɹɛzənt/",
  "contemporary": "/kənˈtɛm.pəˌɹɛɹ.i/",
  "medieval": "/mɪd.ˈiː.vəl/",
  "century": "/ˈsɛn.t͡ʃə.ɹiː/",
  "millennium": "/mɪˈlɛnɪəm/",
  "million": "/ˈmɪljən/",
  "billion": "/ˈbɪljən/",
  "dozen": "/ˈdʌzən/",
  "dawn": "/dɔn/",
  "midday": "/mɪdˈdeɪ/",
  "midnight": "/ˈmɪdˌnaɪt/",
  "overnight": "",
  "night": "/naɪt/",
  "modern": "/ˈmɑdɚn/",
  "recent": "/ˈɹiːsənt/",
  "up-to-date": "/ˌʌp tə ˈdeɪt/",
  "first": "/fɝst/",
  "secondly": "/ˈsɛkəndli/",
  "finally": "/ˈfaɪ.nəl.i/",
  "finish": "/ˈfɪnɪʃ/",
  "immediately": "/əˈmiːdi.ətli/",
  "instant": "/ˈɪnstənt/",
  "moment": "/ˈmoʊmənt/",
  "minute": "/ˈmɪnɪt/",
  "prior": "",
  "former": "",
  "preceding": "",
  "precedent": "",
  "foremost": "",
  "opening": "",
  "initially": "",
  "intermediate": "",
  "midst": "",
  "meantime": "",
  "meanwhile": "",
  "simultaneous": "",
  "ongoing": "",
  "everlasting": "",
  "permanent": "",
  "punctual": "",
  "duration": "",
  "consecutive": "",
  "periodically": "",
  "imminent": "",
  "incidentally": ""
}

export default wordPhonetics
